# $Id$

clean:
	rm -f *~ C[1-4]_CH_EFW_L2_HK.ceh C[1-4]_CH_EFW_INST.ceh \
	C[1-4]_CH_EFW_L[2-3]_P.ceh C[1-4]_CH_EFW_L[2-3]_E.ceh \
	C[1-4]_CH_EFW_L3_SFIT.ceh C[1-4]_CH_EFW_L3_DER.ceh \
	C[1-4]_CH_EFW_L1_P[1-4].ceh C[1-4]_CH_EFW_L1_P[1,3][2,4].ceh \
	C[1-4]_CQ_EFW_INST.ceh C[1-4]_CH_EFW_L1_IB.ceh C[1-4]_CH_EFW_L2_PB.ceh \
	C[1-4]_CH_EFW_L2_EB.ceh C[1-4]_CH_EFW_L2_BB.ceh \
	C[1-4]_CH_AUX_MAARBLE_ULF_PC12.ceh C[1-4]_CH_AUX_MAARBLE_ULF_PC35.ceh
