%
% Get official SWML used by BICAS (as opposed to any future test SWML).
%
%
% NOTE
% ====
% NOTE: There is no SWM for generating VHT datasets(!). VHT processing is
%       therefore not represented here.
% NOTE: The SWMs implemented in the body of BICAS must always be compatible
%       with the SWMs specified here.
%
%
% RETURN VALUES
% =============
% Official bicas.swm.SoftwareModeList object (~singleton) that is actually used
% by BICAS.
%
%
% Author: Erik P G Johansson, IRF, Uppsala, Sweden
%
function Swml = get_SWML(Bso)
% PROPOSAL: Convert into class with static methods.
%   PRO: Clarifies internal functions (three; plus the main one).
%
% PROPOSAL: Replace BSO with arguments for each used setting.
%   CON: BSO (and L) is used by production functions. Can not
%        at all eliminate easily.


swmL1L2Enabled = Bso.get_fv('SWM.L1-L2_ENABLED');

SwmArray = get_SWMs_L1_L1R_to_L2(swmL1L2Enabled);

if Bso.get_fv('SWM.L2-L2_CWF-DSR_ENABLED')
  SwmArray(end+1, 1) = get_SWMs_L2_to_L2();
end

if Bso.get_fv('SWM.L2-L3_SURV_ENABLED')
  SwmArray(end+1, 1) = get_SWMs_L2_to_L3_SURV();
end

if Bso.get_fv('SWM.L2-L3_SBMx_ENABLED')
  SwmArray(end+1, 1) = get_SWMs_L2_to_L3_SBMx(1);
  SwmArray(end+1, 1) = get_SWMs_L2_to_L3_SBMx(2);
end



Swml = bicas.swm.SoftwareModeList(SwmArray);

end







function SwmArray = get_SWMs_L1_L1R_to_L2(swmL1L2Enabled)
% PROPOSAL: Re-implement (top-level) hard-coded constants by setting
%   multiple redundant 1D(?) vectors that covers every case. Then
%   set various cases by assigning constants to many elements using
%   MATLAB syntax. One index representing: Combination of
%   DSI+Skeleton_Version (both pipelines, LFR+TDS, HK+SCI),
%   every element contains data for that dataset. Must use
%   combination DSI+Skeleton_Version to potentially cover old
%   versions. Manipulate and set multiple elements smoothly by using
%   vectors for indices.
%   Ex: Vectors to set: skeletonVersionVector, SBMx_SURV_vector,
%       CWF_SWF_vector, output dataset level, vectors for
%       human-readable description string(s) (e.g. sbmxSurvStrHumanReadable)
%   Ex: Vectors with indices for dataset in/for: either pipeline,
%       science or HK, LFR or TDS, latest versions or
%       backward-compatibility versions.
%   --
%   TODO-DEC: Above describes input & output (?) data sets.
%       How relates to s/w modes?
%
% PROPOSAL: Merge LFR and TDS loops.

% --------------------------------------------------------------
% Constants to iterate over: one element per input level L1/L1R
% --------------------------------------------------------------
% {1} = S/w modes (science) L1R-->L2
% {2} = S/w modes (science) L1 -->L2 (optional)
L1R_INPUT_DATA = struct( ...
  'level',              'L1R', ...
  'optionalInputDashE', '-E', ...    % Added "-E" (or not).
  'swmNameSuffix',      '', ...
  'swmPurposeAmendm',   '');         % Amendment to SWM "purpose string".
L1_INPUT_DATA = struct( ...
  'level',              'L1', ...
  'optionalInputDashE', '', ...
  'swmNameSuffix',      '_L1', ...
  'swmPurposeAmendm',   ' UNOFFICIAL wrt. ROC.');
INPUT_LEVEL_DATA_AR = L1R_INPUT_DATA;
if swmL1L2Enabled
  INPUT_LEVEL_DATA_AR(end+1, 1) = L1_INPUT_DATA;
end



% Define function which replaces specified substrings depending on input level.
% "strmod" = string modify, "g"=global (applies to all s/w modes).
strmodg = @(s, iInputLevel) bicas.utils.strrep_many(s, ...
  '<InLvl>',              INPUT_LEVEL_DATA_AR(iInputLevel).level, ...
  '<I-E>',                INPUT_LEVEL_DATA_AR(iInputLevel).optionalInputDashE, ...
  '<SWM name suffix>',    INPUT_LEVEL_DATA_AR(iInputLevel).swmNameSuffix, ...
  '<SWM purpose amendm>', INPUT_LEVEL_DATA_AR(iInputLevel).swmPurposeAmendm);



%------------------------------------------------------------------------------
% Constants to iterate over: one element per pair (L1/L1R) of SWMs L1/L1R-->L2
%------------------------------------------------------------------------------
LFR_TDS_SKT_VERSION = '18';
LFR_MODE_STR_CA = {...
  'selective burst mode 1', ...
  'selective burst mode 2', ...
  'survey mode', ...
  'survey mode' ...
  };
LFR_SWM_DATA = struct(...
  'sbmxSurvStrAbbrev',        {'SBM1', 'SBM2', 'SURV', 'SURV'}, ...
  'sbmxSurvStrHumanReadable', LFR_MODE_STR_CA, ...
  'cwfSwfStrAbbrev',          {'CWF',  'CWF',  'CWF',  'SWF' }, ...
  'outputSkeletonVersion',    repmat({LFR_TDS_SKT_VERSION}, 1, 4));
TDS_SWM_DATA = struct(...
  'CWF_RSWF',                 {'CWF', 'RSWF'}, ...
  'outputSkeletonVersion',    repmat({LFR_TDS_SKT_VERSION}, 1, 2));



% Input definitions that are reused multiple times.
HK_INPUT_DEF = bicas.swm.InputDataset(...
  'in_hk', 'SOLO_HK_RPW-BIA', 'HK_cdf');
CUR_INPUT_DEF = bicas.swm.InputDataset(...
  'in_cur', 'SOLO_L1_RPW-BIA-CURRENT', 'CUR_cdf');



SwmArray = bicas.swm.SoftwareMode.empty(0, 1);
%==================================================
% Iterate over [L1R] (one component), or [L1, L1R]
%==================================================
for iInputLevel = 1:numel(INPUT_LEVEL_DATA_AR)

  %==================================================
  % Iterate over the "fundamental" **LFR** s/w modes
  %==================================================
  for iSwm = 1:length(LFR_SWM_DATA)

    % Define local string modification function.
    strmod = @(s) bicas.utils.strrep_many(strmodg(s, iInputLevel), ...
      '<SBMx/SURV>',                LFR_SWM_DATA(iSwm).sbmxSurvStrAbbrev, ...
      '<SBMx/SURV human readable>', LFR_SWM_DATA(iSwm).sbmxSurvStrHumanReadable, ...
      '<CWF/SWF>',                  LFR_SWM_DATA(iSwm).cwfSwfStrAbbrev);



    SciInputDataset = bicas.swm.InputDataset(...
      'in_sci', ...
      strmod('SOLO_<InLvl>_RPW-LFR-<SBMx/SURV>-<CWF/SWF><I-E>'), ...
      'SCI_cdf');

    SciOutputDataset = bicas.swm.OutputDataset(...
      'out_sci', ...
      strmod('SOLO_L2_RPW-LFR-<SBMx/SURV>-<CWF/SWF>-E'), ...
      'SCI_cdf', ...
      strmod('LFR L2 <CWF/SWF> science electric <SBMx/SURV human readable> data'), ...
      strmod(...
      ['RPW LFR L2 <CWF/SWF> science electric', ...
      ' (potential difference) data in <SBMx/SURV human readable>,', ...
      ' time-tagged']), ...
      LFR_SWM_DATA(iSwm).outputSkeletonVersion);



    purposeStr = strmod(...
      ['Generate <SBMx/SURV> <CWF/SWF> electric field', ...
      ' L2 data (potential difference)', ...
      ' from LFR <InLvl> data.<SWM purpose amendm>']);
    SwmArray(end+1, :) = bicas.swm.SoftwareMode(...
      bicas.proc.L1L2.LfrSwmProcessing(SciInputDataset.dsi, SciOutputDataset.dsi), ...
      strmod('LFR-<SBMx/SURV>-<CWF/SWF>-E<SWM name suffix>'), ...
      purposeStr, ...
      [SciInputDataset, CUR_INPUT_DEF, HK_INPUT_DEF], ...
      [SciOutputDataset]);
  end



  %==================================================
  % Iterate over the "fundamental" **TDS** s/w modes
  %==================================================
  for iSwm = 1:numel(TDS_SWM_DATA)

    if strcmp(TDS_SWM_DATA(iSwm).CWF_RSWF, 'RSWF') ...
        && strcmp(INPUT_LEVEL_DATA_AR(iInputLevel).level, 'L1')
      % CASE: TDS RSWF
      % Exclude SWM since BICAS can not currently (2023-10-09) read
      % TDS RSWF L1 datasets!
      continue
    end

    % Define local string modification function.
    strmod = @(s) strrep(strmodg(s, iInputLevel), ...
      '<CWF/RSWF>', TDS_SWM_DATA(iSwm).CWF_RSWF);



    SciInputDataset = bicas.swm.InputDataset(...
      'in_sci', ...
      strmod('SOLO_<InLvl>_RPW-TDS-LFM-<CWF/RSWF><I-E>'), ...
      'SCI_cdf');

    SciOutputDataset = bicas.swm.OutputDataset(...
      'out_sci', ...
      strmod('SOLO_L2_RPW-TDS-LFM-<CWF/RSWF>-E'), ...
      'SCI_cdf', ...
      strmod('TDS L2 <CWF/RSWF> science electric LF mode data'), ...
      strmod(...
      ['RPW TDS L2 <CWF/RSWF> science electric (potential', ...
      ' difference) data in LF mode, time-tagged']), ...
      TDS_SWM_DATA(iSwm).outputSkeletonVersion);



    TdsSwmp = bicas.proc.L1L2.TdsSwmProcessing(...
      SciInputDataset.dsi, SciOutputDataset.dsi);
    SwmArray(end+1, :) = bicas.swm.SoftwareMode(...
      TdsSwmp, ...
      strmod('TDS-LFM-<CWF/RSWF>-E<SWM name suffix>'), ...
      strmod(...
      ['Generate <CWF/RSWF> electric field L2 data', ...
      ' (potential difference)', ...
      ' from TDS LF mode <InLvl> data.<SWM purpose amendm>']), ...
      [SciInputDataset, CUR_INPUT_DEF, HK_INPUT_DEF], ...
      [SciOutputDataset]);
  end
end    % for iInputLevel = 1:numel(inputDatasetLevelCa)

end    % get_SWMs_L1_L1R_to_L2







function SwmArray = get_SWMs_L2_to_L2()

SciInputDataset = bicas.swm.InputDataset(...
  'in_sci', ...
  'SOLO_L2_RPW-LFR-SURV-CWF-E', ...
  'OSR_cdf');

SciOutputDataset = bicas.swm.OutputDataset(...
  'out_dsr', ...
  'SOLO_L2_RPW-LFR-SURV-CWF-E-1-SECOND', ...
  'DSR_cdf', ...
  'LFR L2 CWF science electric survey mode data, downsampled', ...
  ['RPW LFR L2 CWF science electric (potential difference)', ...
  ' data in survey mode, time-tagged, downsampled'], ...
  '02');



% NOTE: Function handle: Argument rctDir is not used, but is
% needed for the interface.
SwmArray = bicas.swm.SoftwareMode(...
  bicas.proc.L2L2.LfrDsrSwmProcessing(), ...
  'LFR-SURV-CWF-E-DSR', ...
  ['Generate downsampled version of LFR L2 SURV CWF', ...
  ' science electric (potential difference) data.', ...
  ' NOTE: This is an unofficial s/w mode.'], ...
  [SciInputDataset], ...
  [SciOutputDataset]);

end    % get_SWMs_L2_to_L2







function SwmArray = get_SWMs_L2_to_L3_SURV()

L3_EFIELD_SCPOT_SKT_VERSION = '07';
L3_DENSITY_SKT_VERSION      = '08';

%=======
% INPUT
%=======
SciInputDataset = bicas.swm.InputDataset(...
  'in_sci', ...
  'SOLO_L2_RPW-LFR-SURV-CWF-E', ...
  'LFR-SURV-CWF-E_cdf');

%================
% OUTPUT: 3x OSR
%================
EfieldOutputDataset = bicas.swm.OutputDataset(...
  'out_efield', ...
  'SOLO_L3_RPW-BIA-EFIELD', ...
  'EFIELD_OSR_cdf', ...
  'BIAS L3 science electric field vector data', ...
  'RPW BIAS L3 science electric field vector data, time-tagged', ...
  L3_EFIELD_SCPOT_SKT_VERSION);

ScpotOutputDataset = bicas.swm.OutputDataset(...
  'out_scpot', ...
  'SOLO_L3_RPW-BIA-SCPOT', ...
  'SCPOT_OSR_cdf', ...
  'BIAS L3 science spacecraft potential data', ...
  'RPW BIAS L3 science spacecraft potential data, time-tagged', ...
  L3_EFIELD_SCPOT_SKT_VERSION);

DensityOutputDataset = bicas.swm.OutputDataset(...
  'out_density', ...
  'SOLO_L3_RPW-BIA-DENSITY', ...
  'DENSITY_OSR_cdf', ...
  'BIAS L3 science plasma density data', ...
  'RPW BIAS L3 science plasma density data, time-tagged', ...
  L3_DENSITY_SKT_VERSION);

%================
% OUTPUT: 3x DSR
%================
EfieldDsrOutputDataset = bicas.swm.OutputDataset(...
  'out_efield_dsr', ...
  'SOLO_L3_RPW-BIA-EFIELD-10-SECONDS', ...
  'EFIELD_DSR_cdf', ...
  'BIAS L3 downsampled science electric field vector data', ...
  ['RPW BIAS L3 downsampled science electric', ...
  ' field vector data, time-tagged'], ...
  L3_EFIELD_SCPOT_SKT_VERSION);

ScpotDsrOutputDataset = bicas.swm.OutputDataset(...
  'out_scpot_dsr', ...
  'SOLO_L3_RPW-BIA-SCPOT-10-SECONDS', ...
  'SCPOT_DSR_cdf', ...
  'BIAS L3 downsampled science spacecraft potential data', ...
  ['RPW BIAS L3 downsampled science spacecraft', ...
  ' potential data, time-tagged'], ...
  L3_EFIELD_SCPOT_SKT_VERSION);

DensityDsrOutputDataset = bicas.swm.OutputDataset(...
  'out_density_dsr', ...
  'SOLO_L3_RPW-BIA-DENSITY-10-SECONDS', ...
  'DENSITY_DSR_cdf', ...
  'BIAS L3 downsampled science plasma density data', ...
  ['RPW BIAS L3 downsampled science plasma', ...
  ' density data, time-tagged'], ...
  L3_DENSITY_SKT_VERSION);



%=====
% SWM
%=====
% NOTE: Only creates one SWM for 1x L2 CDF --> 2x3 L3 CDFs.
SwmArray = bicas.swm.SoftwareMode(...
  bicas.proc.L2L3.L3OsrDsrSwmProcessing(false, []), ...
  'L2-L3_SURV', ...
  ['Generate L3 electric field vector, spacecraft', ...
  ' potential, and density data', ...
  ' incl. additional downsampled versions.', ...
  ' NOTE: This is an unofficial s/w mode.'], ...
  [SciInputDataset], ...
  [EfieldOutputDataset, ...
  EfieldDsrOutputDataset, ...
  ScpotOutputDataset, ...
  ScpotDsrOutputDataset, ...
  DensityOutputDataset, ...
  DensityDsrOutputDataset]);

end    % get_SWMs_L2_to_L3_SURV







% EXPERIMENTAL. INCOMPLETE.
% NOTE: Create one of TWO separate SBMx modes.
function SwmArray = get_SWMs_L2_to_L3_SBMx(iSbm)

assert(isscalar(iSbm) & isfloat(iSbm))
assert(ismember(iSbm, [1;2]))

%=======
% INPUT
%=======
% NOTE: PFIID value is independent of SBM1/SBM2.
SbmxInputDataset = bicas.swm.InputDataset(...
  'in_sci', ...
  sprintf('SOLO_L2_RPW-LFR-SBM%i-CWF-E', iSbm), ...   % DSI
  'LFR-SBMx-CWF-E_cdf');                              % PFIID

%========
% OUTPUT
%========
SbmxDensityOutputDataset = bicas.swm.OutputDataset(...
  'out_density', ...
  sprintf('SOLO_L3_RPW-BIA-SBM%i-DENSITY', iSbm), ...    % DSI
  'SBMx_DENSITY_cdf', ...    % PFOID
  sprintf('BIAS SBM%i1 L3 science plasma density data',                 iSbm), ...  % Name in SWD
  sprintf('RPW BIAS SBM%i L3 science plasma density data, time-tagged', iSbm), ...  % Description in SWD.
  '01');

SbmxEfieldOutputDataset = bicas.swm.OutputDataset(...
  'out_efield', ...
  sprintf('SOLO_L3_RPW-BIA-SBM%i-EFIELD',  iSbm), ...
  'SBMx_EFIELD_cdf', ...
  sprintf('BIAS SBM%i1 L3 science electric field  datas',         iSbm), ...
  sprintf('RPW BIAS SBM%i L3 electric field in SRF, time-tagged', iSbm), ...
  '01');

SbmxScpotOutputDataset = bicas.swm.OutputDataset(...
  'out_scpot', ...
  sprintf('SOLO_L3_RPW-BIA-SBM%i-SCPOT',   iSbm), ...
  'SBMx_SCPOT_cdf', ...    % PFOID
  sprintf('BIAS SBM%i1 L3 s/c potential data',                        iSbm), ...
  sprintf('RPW BIAS SBM%i L3 spacecraft potential data, time-tagged', iSbm), ...
  '01');

%=====
% SWM
%=====
SwmArray = bicas.swm.SoftwareMode(...
  bicas.proc.L2L3.L3OsrDsrSwmProcessing(true, iSbm), ...
  sprintf('L2-L3_SBM%i', iSbm), ...   % cliOption
  sprintf( ...
  'Generate L3 SBM%i density, efield+s/c, potential data. NOTE: This is an unofficial s/w mode.', ...
  iSbm), ...
  [SbmxInputDataset], ...
  [SbmxDensityOutputDataset; ...
  SbmxEfieldOutputDataset; ...
  SbmxScpotOutputDataset]);
end    % get_SWMs_L2_to_L3_SBMx
