% IRF_INDENTATIONS ensures uniform 2 space indentations is used in all
% applicable irfu-matlab .m files as per our CONTRIBUTING.md guidelines
%
% 	IRF_INDENTATIONS opens and in applicable cases re-writes all files using
% 	Matlab's own smartIndentContents(). For this to work one should first
%   set appropriate "Tab size = 2" & "Indent size = 2" in the Matlab editor
% 	found under "Matlab" -> "Preferences" -> "Editor/Debugger" -> "Tab".
%
% Note: SolarOrbiter specific code ("mission/solo/") and externally
%       contributed code ("contrib/") is excluded from this 2 space
%       recommendation.
%
% 	See also smartIndentContents, <a href="matlab:web('https://github.com/irfu/irfu-matlab/blob/master/.github/CONTRIBUTING.md')">.github/CONTRIBUTING.md</a>

% Verify settings is two spaces and only two spaces (no tabs or more/less spaces)
s = settings;
if (s.matlab.editor.tab.IndentSize.ActiveValue ~= 2 || ...
    s.matlab.editor.tab.TabSize.ActiveValue ~= 2 || ...
    ~s.matlab.editor.tab.InsertSpaces.ActiveValue)
  logStr = 'Before running "irf_indentations", make sure your indentations are set to two (2) spaces and only spaces, no tabs.';
  irf.log('critical', logStr);
  error(logStr);
end

irfPath = irf('path'); % irf root path

irfDirectories = {...
  '.', ...  % irf root path
  '@dataobj', ...
  '+local', ...
  '+lp', ...
  '+maarble', ...
  '+model', ...
  '+whamp', ...
  'irf', ...
  ['irf'     filesep '+irf'], ...
  ['irf'     filesep '+irf' filesep ''], ...
  ['irf'     filesep '+irf' filesep '+cdf'], ...
  ['irf'     filesep '+irf' filesep '+ds'], ...
  ['irf'     filesep '+irf' filesep '+fs'], ...
  ['irf'     filesep '+irf' filesep '+graph'], ...
  ['irf'     filesep '+irf' filesep '+str'], ...
  ['irf'     filesep '+irf' filesep '+utils'], ...
  ['mission' filesep 'cluster'], ...
  ['mission' filesep 'cluster' filesep 'c_ri'], ...
  ['mission' filesep 'cluster' filesep 'caa'], ...
  ['mission' filesep 'cluster' filesep 'caa' filesep '@ClusterDB'], ...
  ['mission' filesep 'cluster' filesep 'caa' filesep '@ClusterProc'], ...
  ['mission' filesep 'mms'], ...
  ['mission' filesep 'mms' filesep '+mms'], ...
  ['mission' filesep 'mms' filesep 'cal'], ...
  ['mission' filesep 'mms' filesep 'mms_testFunctions'], ...
  ['mission' filesep 'rosetta'], ...
  ['mission' filesep 'solar_orbiter'], ...
  ['mission' filesep 'solar_orbiter' filesep '+solo'], ...
  ['mission' filesep 'solar_orbiter' filesep '+solo' filesep '+BSACT_utils'], ...
  ['mission' filesep 'solar_orbiter' filesep '+solo' filesep '+adm'], ...
  ['mission' filesep 'solar_orbiter' filesep '+solo' filesep '+hwzv'], ...
  ['mission' filesep 'solar_orbiter' filesep '+solo' filesep '+qli'], ...
  ['mission' filesep 'solar_orbiter' filesep '+solo' filesep '+shk'], ...
  ['mission' filesep 'solar_orbiter' filesep '+solo' filesep '+sp'], ...
  ['mission' filesep 'themis'], ...
  ['mission' filesep 'thor'], ...
  ['mission' filesep 'thor' filesep 'orbit_coverage'], ...
  ['mission' filesep 'thor' filesep 'plots'], ...
  'plots', ...
  ['plots'   filesep 'mms'], ...
  ['plots'   filesep 'solo']
  };

for iPath = 1:numel(irfDirectories)
  mFiles = dir([irfPath, filesep, irfDirectories{iPath}, filesep, '*.m']);
  for iFile = 1:length(mFiles)
    theDocument = matlab.desktop.editor.openDocument(fullfile(mFiles(iFile).folder, mFiles(iFile).name));
    smartIndentContents(theDocument);
    save(theDocument);
    close(theDocument);
  end
end

