%
% swdmd = SWD metadata
%
% Class for setting one non-trivial constant (data structure) for setting SWD
% metadata.
%
%
% Author: Erik P G Johansson, IRF, Uppsala, Sweden
%
classdef swdmd



  %###########
  %###########
  % CONSTANTS
  %###########
  %###########
  properties(Constant)



    SWD_METADATA = bicas.const.swdmd.init_SWD_metadata();



  end



  %########################
  %########################
  % PRIVATE STATIC METHODS
  %########################
  %########################
  methods(Static, Access=private)



    % Various SWD release data for the entire software (not specific outputs).
    function MAP = init_SWD_metadata()
      MAP = containers.Map();

      IRF_LONG_NAME = 'Swedish Institute of Space Physics (IRF)';
      %
      MAP('SWD.identification.project')     = 'ROC';
      MAP('SWD.identification.name')        = 'BIAS Calibration Software (BICAS)';
      MAP('SWD.identification.identifier')  = 'BICAS';
      MAP('SWD.identification.description') = ...
        ['Calibration software meant to be run at LIRA/ROC to' ...
        ' (1) calibrate electric field L2 data from' ...
        ' electric L1R LFR and TDS-LFM data, and' ...
        ' (2) calibrate bias currents from L1 data.' ...
        ' It also has additional unofficial support for' ...
        ' (1) processing L1 (instead of L1R; partial support) to L2,' ...
        ' (2) L2 LFR CWF to L2 LFR CWF downsampled (unofficial dataset), and' ...
        ' (3) BIAS L2 to L3 data', ...
        ' (all disabled by default).'];

      % 2024-09-13: Latest released RCS ICD version is 01/07.
      MAP('SWD.identification.icd_version') = '1.7';

      % ROC-GEN-SYS-NTT-00019-LES, "ROC Engineering Guidelines for External
      % Users":
      % """"""""
      % 2.2.3 RCS versioning
      % The RCS version must be a unique number sequence identifier
      % “X.Y.Z”, where “X” is an integer indicating the release (major
      % changes, not necessarily retro-compatible), “Y” is an integer
      % indicating the issue (minor changes, necessarily retro-compatible)
      % and “Z” is an integer indicating a revision (e.g., bug
      % correction).
      % """"""""
      %
      %  ROC-PRO-PIP-ICD-00037-LES, "RPW Calibration Software Interface
      %  Control Document", 01/07:
      % """"""""
      % "version": Current version of the S/W. The RCS version shall be a unique
      % number sequence identifier “X.Y.Z”, where “X” is an integer indicating
      % the release (major changes, not necessarily retro-compatible), “Y” is an
      % integer indicating the issue (minor changes, necessarily
      % retro-compatible) and “Z” is an integer indicating a revision (e.g., bug
      % correction). The first stable release of software (S/W) must have its
      % major number “X” equals to 1, its minor number “Y” equals to 0 and its
      % revision number “Z” equals to 0 (i.e., “1.0.0”). S/W preliminary
      % versions (e.g., alpha, beta, etc.) must have their version number “X”
      % equals to 0 and must not have a character as a prefix/suffix (“0.Y.Zb”
      % for the 0.Y.Z beta version for instance). In all cases, any change in
      % the S/W must lead to update the version number.
      % """"""""
      MAP('SWD.release.version')   = '9.4.0';
      MAP('SWD.release.date')      = '2026-07-28T17:15:00Z';
      MAP('SWD.release.author')    = 'Erik P G Johansson, BIAS team, IRF';
      MAP('SWD.release.contact')   = 'erik.johansson@irf.se';
      MAP('SWD.release.institute') = IRF_LONG_NAME;
      % 'Various updates and refactoring; close to complete support for
      % LFR & TDS datasets (but untested); Removed ROC-SGSE_* dataset
      % support.' 'Almost-complete support for LFR & TDS datasets
      % (voltages) with transfer functions (partially tested).'
      % /Earlier version
      %
      % ========================
      % SWD.release.modification
      % ========================
      % NOTE: Since BICAS supports some unofficial processing, this
      % description should maybe not describe modifications related to
      % such unofficial processing.
      %
      % SWD.release.modification = ...
      % ['Modified default settings: inverted transfer function', ...
      % ' cutoff at 0.8*omega_Nyquist, duplicate bias current gives error'];
      % /v3.1.1
      % MAP('SWD.release.modification') = ...
      %     ['Non-Standard Operations (NSO) table for setting QUALITY_FLAG, L2_QUALITY_BITMASK (new)', ...
      %     '; Set glob.attr. Datetime, OBS_ID, SOOP_TYPE, TIME_MIN, TIME_MAX', ...
      %     '; Modified default setting: PROCESSING.L1R.LFR.ZV_QUALITY_FLAG_BITMASK_EMPTY_POLICY=ERROR'];   % v4.0.0
      % MAP('SWD.release.modification') = ...
      %     ['Non-Standard Operations (NSO) table for thruster firings up until 2020-12-05', ...
      %     '; Zero order AC detrending, no AC re-trending', ...
      %     '; Combined transfer functions (LFR+BIAS) modified during', ...
      %     ' execution to have constant gain for low freqs. for AC data', ...
      %     '; Bugfix: glob.attr. Datetime, OBS_ID, SOOP_TYPE', ...
      %     '; Bugfix: not crashing when reading CURRENT datasets with one bias setting'];   % v4.1.0
      % MAP('SWD.release.modification') = ...
      %     ['Non-Standard Operations (NSO) table for thruster firings', ...
      %     ' & saturation up until 2021-01-26', ...
      %     '; Better output CDF standards compliance', ...
      %     '; Using new master CDFs']; % v5.0.0
      % MAP('SWD.release.modification') = ...
      %     ['Non-Standard Operations (NSO) table for thruster firings', ...
      %     ' & saturation up until 2021-09-21', ...
      %     '; Setting zVar attributes', ...
      %     ' SCALEMIN & SCALEMAX using zVar min & max values', ...
      %     '; Using new L2 master CDFs', ...
      %     '; Less excessive log messages for processing L1/L1R-->L2 LFR SWF', ...
      %     '; Permits HK and science input datasets to not overlap at', ...
      %     ' all in order to salvage some LFR DC data.']; % v6.0.0
      % MAP('SWD.release.modification') = [...
      %     'Non-Standard Operations (NSO) table for thruster firings', ...
      %     ' & saturation up until 2022-09-03', ...
      %     '; Bugfix: Use LFR''s R0/R1/R2 for splitting time into', ...
      %     ' time intervals', ...
      % ]; % v6.0.1
      % MAP('SWD.release.modification') = [...
      %     'Non-Standard Operations (NSO) table for thruster firings', ...
      %     ' updated for up until 2022-12-17', ...
      %     '; Bugfix: Corrected algorithm/formula for calculating Ez_SRF (vdccal.m).', ...
      %     '; Recalculated and added E-field calibration data.', ...
      %     ' Now covers 2020-02-28 to 2022-12-03.'
      % ]; % v6.0.2
      % MAP('SWD.release.modification') = [...
      %     'Non-Standard Operations (NSO) table for thruster firings', ...
      %     ' updated for up until 2023-02-05', ...
      %     '; Uses new master CDFs.'
      % ]; % v7.0.0
      % MAP('SWD.release.modification') = [...
      %     'Non-Standard Operations (NSO) table for thruster firings', ...
      %     ' updated for up until 2024-01-11', ...
      %     '; Uses new L3 master CDFs without \"LFR\".', ...
      %     '; Support demultiplexer latching relay changing.', ...
      %     '; Autodetects saturation.', ...
      %     '; New L3 density quality bit.', ...
      %     '; Detect sweeps for exclusion using algorithm.' ...
      % ]; % v8.0.0
      % MAP('SWD.release.modification') = [...
      %   'Non-Standard Operations (NSO) table for thruster firings', ...
      %   ' updated for up until 2024-01-30', ...
      %   '; Cap QUALITY_FLAG at 3 (instead of 2)', ...
      %   '; Bugfix for automatic sweep detection (SCDA)', ...
      %   '; Corrected documentation w.r.t. CDF format version.' ...
      %   '; Changed source code style', ...
      %   ]; % v8.0.1
      % MAP('SWD.release.modification') = [...
      %   'Require MATLAB R2024a (instead of R2019b)', ...
      %   '; Non-Standard Operations (NSO) table for thruster firings', ...
      %   ' updated for up until 2024-05-05', ...
      %   ]; % v8.1.0
      % MAP('SWD.release.modification') = [...
      %   'Updates for L2 dataset compliance, requiring new master CDFs (V15)', ...
      %   '; Require RCT on new filenaming convention', ...
      %   '; Non-Standard Operations (NSO) table for thruster firings', ...
      %   ' updated for up until 2024-05-19', ...
      %   ]; % v8.2.0
      % MAP('SWD.release.modification') = [...
      %   'Bugfix: Including previously missing source code updates.', ...
      %   ]; % v8.2.1
      % MAP('SWD.release.modification') = [...
      %   'Non-Standard Operations (NSO) table for thruster firings updated', ...
      %   ' for until 2024-08-04', ...
      %   '; Use bias_rct_validity.json to locate BIAS RCT', ...
      %   ]; % v8.3.0
      % MAP('SWD.release.modification') = [...
      %   'Non-Standard Operations (NSO) table for thruster firings updated', ...
      %   ' for until 2025-02-10', ...
      %   '; Use new L2 master CDFs V17.', ...
      %   ]; % v8.4.0
      % MAP('SWD.release.modification') = [...
      %   'Non-Standard Operations (NSO) table for thruster firings updated', ...
      %   ' for until 2025-02-16', ...
      %   '; Bugfix: L2_QUALITY_BITMASK saturation bits', ...
      %   '; Use new L3 master CDFs V06/V07.', ...
      %   ]; % v8.4.1
      % MAP('SWD.release.modification') = [...
      %   'Non-Standard Operations (NSO) table for thruster firings updated', ...
      %   ' for until 2025-05-27', ...
      %   '; Bugfix: Can now handle multi-valued GA "OBS_ID"', ...
      %   '; Bugfix: SOLO_L3_RPW-BIA-DENSITY-10-SECONDS ZV QUALITY_FLAG is now a', ...
      %   ' downsampled version of SOLO_L3_RPW-BIA-DENSITY ZV QUALITY_FLAG.', ...
      %   '; No longer set L3 QUALITY_FLAG and L3_QUALITY_BITMASK to FV when', ...
      %   ' there is no science data.', ...
      %   ]; % v8.5.0
      % MAP('SWD.release.modification') = [...
      %   'Non-Standard Operations (NSO) table for thruster firings updated', ...
      %   ' for until 2025-12-01', ...
      %   '; Redefined L2 L2_QUALITY_BITMASK: Separate saturation quality bits for different channels (backward-incompatible change)', ...
      %   '; Adjusts fill values & quality variables when ANT3 is failing or unintentionally floating.', ...
      %   '; Use new L2 master CDFs V18, L3 master CDFs V07/V08.', ...
      %   ]; % v9.0.0
      % MAP('SWD.release.modification') = [...
      %   ['Add density calibration data for 2023-12-17 in psp2ne().' ...
      %   ' SCPOT, EFIELD, DENSITY datasets get improved QUALITY_FLAG, data' ...
      %   ' filtering, and are potentially generated when ANT3 fails.'], ...
      %   ]; % v9.1.0
      % MAP('SWD.release.modification')   = [...
      %   ['Fix E-field/spacecraft pot./PSP calibration code, fix psp2ne()' ...
      %   ' calibration data. L3 makes use of new L2_QUALITY_BITMASK.'], ...
      %   ]; % v9.2.0
      % MAP('SWD.release.modification')   = [...
      %   ['New SCPOT+EFIELD calibration data'], ...
      %   ]; % v9.3.0
      MAP('SWD.release.modification')   = [...
        ['Non-Standard Operations (NSO) table for thruster firings updated', ...
        ' for until 2026-07-26'], ...
        ]; % v9.4.0

      MAP('SWD.release.source')         = 'https://github.com/irfu/irfu-matlab/commits/SOdevel';
      % Appropriate branch? "master" instead?
      %
      % Relative path to BICAS executable. See RCS ICD.
      MAP('SWD.environment.executable') = 'roc/bicas';



      %======================
      % ASSERTIONS: SETTINGS
      %======================
      irf.assert.castring_regexp(MAP('SWD.release.version'), ...
        '[0-9]+\.[0-9]+\.[0-9]+')
      irf.assert.castring_regexp(MAP('SWD.release.date'), ...
        '20[1-3][0-9]-[01][0-9]-[0-3][0-9]T[0-2][0-9]:[0-5][0-9]:[0-6][0-9]Z')
      % Validate S/W release version
      % ----------------------------
      % RCS ICD 00037, iss1rev2, Section 5.3 S/W descriptor file
      % validation scheme implies this regex.
      % NOTE: It is hard to thoroughly follow the description, but the end
      % result should be under release-->version-->pattern (not to be
      % confused with release_dataset-->version--pattern).
      irf.assert.castring_regexp(MAP('SWD.release.version'), '(\d+\.)?(\d+\.)?(\d+)')
    end



  end    % methods(Static, Access=private)



end
