#!/bin/bash
#====================================================================================================
# Author: Erik P G Johansson, IRF-U, Uppsala, Sweden
# First created 2016-04-xx
#
# The primary purpose of this bash script is to call a MATLAB script.
# See the MATLAB script called for more documentation.
#
#
# 
# PARAMETERS: [--developer-bash-settings]   --log <dir>   <Other arguments>
#
# --developer-bash-settings : Unofficial flag for using particular settings.
# --log <dir>               : Path to directory where log file will be created. 
# <Other arguments>         : Argument parsed in the MATLAB code.
# NOTE: Only the placement of the first flag --developer-bash-settings is important.
#
#
# NOTE: The script reads the "--log" parameter value and pipes "all" stdout to a log file. 
# It also uses a prefix to filter out some stdout lines that are piped to the actual stdout.
# In addition, a symlink (with a constant filename) to the current log file is created.
# Overwriting the old symlink might technically not be compliant with the RCS ICD.
# 
# NOTE: The script takes stderr and copy it to the log file with a prefix.
# 
# NOTE: The script is designed to handle important basic errors, such as
# 1) Can not find MATLAB executable (not explicitly, but implicitly)
# 2) MATLAB can not find the MATLAB script.
# 
# NOTE: The script is designed to return the same exit codes as the MATLAB code.
# 
# 
# 
# IMPLEMENTATION NOTE: Reasons to pipe MATLAB's stdout to the log file
# from this bash script rather than from MATLAB code:
# 1) avoid manually having to pipe everything to log file in MATLAB code.
# 2) can handle stdout from library MATLAB code that prints to stdout (code that should not be altered, e.g. in irfu-matlab, e.g. irf.log)
# 3) can handle stdout from the MATLAB startup process
# 
# IMPLEMENTATION NOTE: The same arguments that are passed to this script are passed on to the MATLAB code, including
# arguments which are unnecessary there, including --log <dir> and --developer-bash-settings.
# PRO (Reasons for):
# 1) It is best to let as much parameter-parsing (incl. syntax checking) code to be in one place as possible (the MATLAB code).
# 2) Enable the MATLAB code to print all the command-line parameters in error messages and to the log file.
# 3) Enable the MATLAB code to print its syntax which is then identical to the syntax of this script.
# CON: The MATLAB code needs some knowledge of the parameter parsing in this script.
#
# IMPLEMENTATION NOTE: The name of this file may only contain alphanumeric characters. Can therefore not use 
# the file extension ".sh" to indicate that it is a shell script.
# /ROC-TST-GSE-ICD-00023-LES, iss02rev02, Section 3.1.
# 
#====================================================================================================
# QUESTION: If log file already exists, overwrite, amend, or error?
# PROPOSAL: Use config file for determining which MATLAB version to launch?
#    PRO: Useful for launching on different systems. Could abolish --bash-developer-settings
#    PROPOSAL: Simply source bash code?
#    PROPOSAL: S/W mode descriptor activation fields could also be used.
#       CON: Must the use that when launching locally.
#====================================================================================================



# Search pattern that determines which stdout (in particular
# from MATLAB) that is actually piped to stdout.
# NOTE: This pattern must match the corresponding prefix used in MATLAB.
declare -r STDOUT_PATTERN='^STDOUT: '    # NOTE: Regex. Includes "^" = beginning of line.

declare -r STDERR_PREFIX='STDERR: '   # NOTE: Not a regex!

# Name of script such as it is called from inside MATLAB, i.e. WITHOUT file extension.
declare -r MATLAB_SCRIPT_NAME="bicas"







#========================================
# Extract relevant (optional) arguments:
# (1) log directory
# (2) config file
#========================================
for ((i=1; i<$#; i++))      # NOTE: Intentionally omit the last argument.
do
    if [[ "${!i}" == "--log" ]]
    then
        let j=i+1
        declare -r log_dir="${!j}"
    elif [[ "${!i}" == "--config" ]]
    then
        let j=i+1
        declare -r config_file_argument="${!j}"
    fi
done







#===================================================================================
# Find (absolute) paths by using the path to this executable + relative paths.
# Assumes that this executable is located under a subdirectory of $BICAS_ROOT_PATH.
#===================================================================================
temp=$(dirname "$0")/..
declare -r BICAS_ROOT_PATH=$(readlink -f "$temp")
declare -r BICAS_MATLAB_CODE_SRC_PATH="${BICAS_ROOT_PATH}/src/"
declare -r DEFAULT_CONFIG_FILE="${BICAS_ROOT_PATH}/config/bicas.conf"







#=====================================
# Construct path and name of log file
#=====================================
if [[ ! -z "$log_dir" ]]
then
    if [[ ! -d "$log_dir" ]] ; then
        echo "Can not find specified log directory \"$log_dir\"." >> /dev/stderr
        exit 1
    fi
    base=$(basename "$0")
    timestamp=$(date +%Y-%m-%d_%H.%M.%S)   # LOCAL time, not UTC.
    log_file="${log_dir}/${base}_${timestamp}.log"
    log_file_symlink="${log_dir}/${base}_latest.log"
    
    
    
    #=====================================================
    # Test if can create (write) to the proposed log file
    #=====================================================
    touch "$log_file"
    if [[ $? != 0 ]] ; then
        echo "Can not write to log file \"$log_file\"." >> /dev/stderr
        exit 1
    fi



    #=================================================================
    # Create symlink to latest/current log.
    # NOTE: This may technically be in violation of the RSC ICD 
    # when removing/overwriting an old symlink.
    # 
    # test options:
    #        -h FILE
    #               FILE exists and is a symbolic link (same as -L)
    # 
    # ln options:
    #        -r, --relative
    #               create symbolic links relative to link location
    #=================================================================
    if [[ -h "$log_file_symlink" ]] ; then
        rm -v "$log_file_symlink" >> "$log_file"
    fi
    ln -srv "$log_file" "$log_file_symlink" >> "$log_file"

else
    log_file='/dev/null'
fi



#==================================
# Determine config file and run it
#==================================
if [[ -z "$config_file_argument" ]] ; then
    config_file="$DEFAULT_CONFIG_FILE"
else
    config_file="$config_file_argument"
fi
if [[ ! -f "$config_file" ]] ; then
    echo "Can not find configuration file \"$config_file\"." >> /dev/stderr
    exit 1
fi
source "$config_file"   # Sets IRFU_MATLAB_PATH, MATLAB_COMMAND.
declare -r IRFU_MATLAB_PATH=$(cd "$BICAS_ROOT_PATH" ; readlink -f "$IRFU_MATLAB_PATH")   # NOTE: Changes value of the same variable.



# DEBUG
# echo log_dir  = "$log_dir"
# echo log_file = "$log_file"
# echo log_file_symlink = "$log_file_symlink"



# DEBUG: Always piped to the actual stdout. Useful for debugging.
# echo "BICAS_ROOT_PATH             = \"$BICAS_ROOT_PATH\""
# echo "BICAS_MATLAB_CODE_SRC_PATH  = \"$BICAS_MATLAB_CODE_SRC_PATH\""
# echo "MATLAB_COMMAND              = \"$MATLAB_COMMAND\""
# echo "IRFU_MATLAB_PATH            = \"$IRFU_MATLAB_PATH\""
# echo "config_file                 = \"$config_file\""
# echo "log_file                    = \"$log_file\""



echo "Command-line arguments: $@" >> "$log_file"



# Any call to this function should appropriately pipe stdout, stderr.
# Therefore there should be no need to pipe inside it.
launch_matlab_code() {

    echo "BICAS_ROOT_PATH             = \"$BICAS_ROOT_PATH\""
    echo "BICAS_MATLAB_CODE_SRC_PATH  = \"$BICAS_MATLAB_CODE_SRC_PATH\""
    echo "MATLAB_COMMAND              = \"$MATLAB_COMMAND\""
    echo "IRFU_MATLAB_PATH            = \"$IRFU_MATLAB_PATH\""
    echo "config_file                 = \"$config_file\""
    echo "log_file                    = \"$log_file\""



    #=======================================================================
    # Convert arguments into one long string that MATLAB code
    # can interpret as a list of arguments.
    # NOTE: Can not handle arguments containing the character single quote.
    #=======================================================================
    matlab_arg_list=""
    for arg in "$@"
    do
        if [[ -z "$matlab_arg_list" ]]   # if string is empty
        then
            matlab_arg_list="'$arg'"
        else
            matlab_arg_list="$matlab_arg_list, '$arg'"
        fi
    done



    #=============================================================================
    # MATLAB options:
    #
    #     -r MATLAB_command    - Start MATLAB and execute the MATLAB_command.
    #     -nodesktop           - Do not start the MATLAB desktop. Use the current
    #                            terminal for commands. The Java virtual machine
    #                            will be started.
    #     -nojvm               - Shut off all Java support by not starting the
    #                            Java virtual machine. In particular the MATLAB
    #                            desktop will not be started.
    #     -nosplash            - Do not display the splash screen during startup.
    #
    # NOTE: The MATLAB code supplied here is to make sure that the code works well in case of failure.
    # 1) MATLAB will NOT EXIT unless the code itself calls "exit".
    # 2) MATLAB hangs if it can not find the MATALB script.
    # NOTE: It is very important to end lines with semicolons and backslash for
    # the command line-supplied MATLAB code to not yield syntax error AND NOT HANG.
    # 
    # NOTE: Do not change directory, so that the current working directory is the same
    # in MATLAB as here. This is necessary for MATLAB code to correctly interpret relative paths (arguments).
    #=============================================================================
    echo "Launching MATLAB, using \"${MATLAB_COMMAND}\"."
    "${MATLAB_COMMAND}" -nodisplay -r "\
        try;\
            addpath(genpath('${IRFU_MATLAB_PATH}'),           '-begin');\
            addpath(genpath('${BICAS_MATLAB_CODE_SRC_PATH}'), '-begin');\
            error_code = $MATLAB_SCRIPT_NAME($matlab_arg_list);\
            quit(error_code);\
        catch e;\
            msg = sprintf('Could not launch the MATLAB script. The reason MIGHT be that MATLAB could not find it.\nException message: %s\n', e.message);\
            fprintf(1, msg);\
            fprintf(2, msg);\
            quit(1);\
        end"
    matlab_error_code=$?
    echo "Bash launch function: matlab_error_code = $matlab_error_code"    # NOTE: Printed to stdout ==> Piped to log file.
    
    
    
    # NOTE: "exit" inside a bash function does NOT EXIT the entire script file.
    exit $matlab_error_code
}



#===========================================================================================================================
# Function for sending (copying) the stderr to a log file (amending). Every row of stderr is prefixed in the log file.
# 
# NOTE: It is possible to use the same (stderr) log file for other logging (stdout) at the same time.
# The order between stdout and stderr is not guaranteed then.
# ASSUMES: stderr itself never contains the prefix. If so, the string is removed.
#===========================================================================================================================
log_stderr() {
    local log_file_stderr="$1"
    shift
    #===========================================================================================================================
    # The functionality requires some bash tricks:
    # 1) One can only pipe stdout and "tee -a" (which copies stdout to file) only works on stdout.
    #    Therefore switches stderr and stdout and pipes. Then, outside that shell (the brackets), switches them back again.
    # 2) We want function to return the error code of the first, innermost command. Must therefore exit inner shell with
    #    exit ${PIPESTATUS[0]} and then the whole function with it again.
    # 
    # tee options:
    #        -a, --append
    #               append to the given FILEs, do not overwrite
    #===========================================================================================================================
    ( eval "$@" 3>&1 1>&2 2>&3 | sed "s/^/${STDERR_PREFIX}/" | tee -a "$log_file_stderr" | sed "s/^${STDERR_PREFIX}//" ; exit ${PIPESTATUS[0]} ) 3>&1 1>&2 2>&3
    exit ${PIPESTATUS[0]}
}



if [[ -z "$log_dir" ]]
then
    # CASE: No log file specified.
    
    launch_matlab_code "$@"                      | grep "$STDOUT_PATTERN" | sed "s/${STDOUT_PATTERN}//"
    matlab_error_code=${PIPESTATUS[0]}    # Get exit code of the first component of piping.
else
    # CASE: Log file specified.
    
    # Launch MATLAB and do nothing with stderr.
    #launch_matlab_code "$@" | tee -a "$log_file" | grep "$STDOUT_PATTERN" | sed "s/${STDOUT_PATTERN}//"
    
    # Launch MATLAB and COPY stderr to the log file (where stderr is prefixed).
    log_stderr "$log_file" launch_matlab_code "$@" | tee -a "$log_file" | grep "$STDOUT_PATTERN" | sed "s/${STDOUT_PATTERN}//"
    
    matlab_error_code=${PIPESTATUS[0]}    # Get exit code of the first component of piping.
fi



exit $matlab_error_code
