% plot figure showing typical plasma densities and temperatures
% Figure 1 of PPCF paper

function InSitu_beta
% beta = 0.4 n[cc] T[eV] / B^2[nT²]
% e- plasma freq [kHz]    = 9 sqrt(n [cc])
% e- gyrofreq [Hz]        = 28 B[nT]
% fp/fce = 9/28 sqrt(n[cc])/B[nT]

beta_range=[1e-3 1e2]; % plasma beta
fpfce_range=[3e-1 3e3]; % fce/fp

flag_plot_caption=input('To write also caption? y/n >','s');

figure(1);
if strcmp(flag_plot_caption,'y')
    set(1,'Position',[0 0 600 1000]);
    clf;
    h=subplot(2,1,1);
else
    set(1,'Position',[0 0 600 350]);
    clf;
    h=subplot(1,1,1);
end

set(gca,'xscale','log','xlim',beta_range);
set(gca,'yscale','log','ylim',fpfce_range);
color_order=[0 0 0;1 0 0;0 0 1;0 0.6 0; 1 0 1];
set(gca,'linewidth',2,'MinorGridLineStyle','none','FontSize',14, ...
    'ColorOrder',color_order);
grid on;hold on;
ylabel('f_{p}/f_{ce}');
xlabel('\beta');

hp=patch([beta_range(1) .1 10 10 3 .1 beta_range(1)],[3 3 6 60 300 300 30],[0.8 1 0.8]);
set(hp,'FaceAlpha',0,'LineWidth',2,'edgecolor','none')
text_square(beta_range(1)* [ 1 100],fpfce_range(2)*[1 .5],1,[0.8 1 0.8],{'Earth magnetosphere'});
text_square(beta_range(1)* [ 1 100],fpfce_range(2)*[.5 .5^2],1,0,{'astrophysical plasmas'});


text_square([.001 0.1],[3 30],1,[0.8 1 0.8],{'Lobes'});
text_square([1 1.1],[70 71],1.3,-1,{'Magnetopause'});
%text_square([.2 20],[6 60],1,[0.8 1 0.8],{' Plasma sheet'});
text_square([.2 20],[6 60],1.3,-1,{' Plasma sheet'});
text_square([.08 3],[60 300],1.3,-1,{' Solar wind'});
text_square([.001 0.03],[.3 3],0.8,0,{' Lower corona'});
text_square([.04 0.2],[3 30],1.2,0,{'Corona'});
text_square([.1 10],[100 500],1.3,0,{' Outer corona'});
text_square([.05 .8],[5 200],1.2,0,{'Laboratory'});
text_square([1 1e2],[20 4e2],1.3,0,{'Supernova remnants'});
text_square([20 20],[2e3 2e3],1.3,0,{'Interstellar medium'});
%text_square([.015 0.1],[20 200],1,'y',{'Reconnection','','\beta<<1','lobes'})

% draw lines of plasma in convergent magnetic field beta=1/B^2
% fp/fce=1/B=sqrt(beta)
%beta_start=1e-2;
%beta_grid=beta_start:.1:beta_range(2);
%fpfce_b_converg=fpfce_range(1)*sqrt(beta_grid/beta_start);
%line(beta_grid,fpfce_b_converg);
%text(beta_grid(1),fpfce_b_converg(1),'   plasma in convergent magnetic field','rotation',20,'verticalalignment','bottom','fontsize',12)

%title('Cross-Scale science in different plasmas');
if strcmp(flag_plot_caption,'y')
    % info line
    ht=text(beta_range(1)*1.1,fpfce_range(2)*0.95,['generated by InSitu\_beta.m ' datestr(now)] );
    set(ht,'fontsize',6,'horizontalalignment','left','verticalalignment','top');
    subplot(2,1,2);axis off
    plasmainfo=' lobes - B=10-30 nT, n=.1-1, T=100-200eV\newline ';
    plasmainfo=[plasmainfo 'plasma sheet B=5-20nT, n=.1-1cc, T=1-10keV \newline '];
    plasmainfo=[plasmainfo 'solar wind B=2-5nT, n=1-4cc, T=1-10eV \newline '];
    plasmainfo=[plasmainfo 'corona B=10^6nT, n=10^9cc, T=100-300eV \newline '];
    text(0,1,plasmainfo)
end

% -----------------------------------------
function [hp,ht]=text_square(xint,yint,z,color,textit)
if min(-1 == color)==1, % if color is -1 only bold text
    %hl=line([xint(1) xint(2) xint(2) xint(1) xint(1)], [yint(1) yint(1) yint(2) yint(2) yint(1)],[z z z z z]);
    ht=text(sqrt(xint(1)*xint(2)),sqrt(yint(1)*yint(2)),z,textit);
    set(ht,'fontsize',14,'HorizontalAlignment','center','VerticalAlignment','middle','interpreter','tex');
elseif min(0 == color)==1, % if color is 1 only text in italic
    %hl=line([xint(1) xint(2) xint(2) xint(1) xint(1)], [yint(1) yint(1) yint(2) yint(2) yint(1)],[z z z z z]);
    ht=text(sqrt(xint(1)*xint(2)),sqrt(yint(1)*yint(2)),z,textit);
    set(ht,'fontsize',12,'fontangle','italic','HorizontalAlignment','center','VerticalAlignment','middle','interpreter','tex');
else
    hp=patch([xint(1) xint(2) xint(2) xint(1)], [yint(1) yint(1) yint(2) yint(2)],[z z z z], color);
    set(hp,'FaceAlpha',0,'LineWidth',2,'edgecolor','none')
    ht=text(sqrt(xint(1)*xint(2)),sqrt(yint(1)*yint(2)),z,textit);
    set(ht,'fontsize',14,'HorizontalAlignment','center','VerticalAlignment','middle','interpreter','tex');
end
end
end

% Here comes all the comments and literature used when creating figure. 

%SOLAR WIND
%Hellinger et all., GRL 2006. Typical solar wind beta values basedon WIND/SWE stastistics over >5 years
%beta peaks around 1. and the characteristic interval is about 0.08 < beta < 3

