% plot figure showing typical temporal and spatial scales and doppler
% shifts for solar orbiter plasma conditions
function Xscale_scales
%NaturalConstants

f_range=[1e-3 2e5];t_range=fliplr(1./f_range); % frequencies in Hz
l_range=[1e-3 1e6]; % wave length in km 
l_inv_range=fliplr(1./l_range); % inverse wave length
l_deb_range=[10e-3 400e-3]; l_inv_deb_range=fliplr(1./l_deb_range);
l_erho_range=[.5 10]; l_inv_erho_range=fliplr(1./l_erho_range);
l_rho_range=[50 1500]; l_inv_rho_range=fliplr(1./l_rho_range);
f_cp_range=[.15 1.5];t_cp_range=1./f_cp_range; % H+ gyrofrequency
f_ce_range=[300 3e3];t_ce_range=1./f_ce_range; % H+ gyrofrequency
f_pe_range=[4e3 50e3];t_pe_range=1./f_pe_range; % H+ gyrofrequency
f_lh_range=40*f_cp_range; t_lh_range=1./f_lh_range; % lower hybrid freq
v=[100 1000 1e4 3e5]; % velocity lines in km/s

figure(1);clf;
h=subplot(1,1,1);
set(gca,'xscale','log','xlim',l_range);
set(gca,'yscale','log','ylim',t_range);
color_order=[0 0 0;1 0 0;0 0 1;0 0.6 0; 1 0 1];
set(gca,'linewidth',2,'MinorGridLineStyle','none','FontSize',14, ...
    'ColorOrder',color_order);
grid on;hold on;
f_v_doppler_lines=repmat(l_range,length(v),1);
f_v_doppler_lines(:,1)=1./f_v_doppler_lines(:,1).*v';
f_v_doppler_lines(:,2)=1./f_v_doppler_lines(:,2).*v';
hp=plot(l_range,1./f_v_doppler_lines);
set(hp,'linewidth',2);
ylabel('time scale [s]');
xlabel('spatial scale [km]');
for jj=1:length(v);
    ttt=['v= ' num2str(v(jj)) ' km/s'];
    ht=text(l_range(1)*11,t_range(2)*0.95*0.5^jj,ttt);
    set(ht,'FontSize',14,'VerticalAlignment','top','Color',color_order(jj,:));
end

% info line
ht=text(l_range(1)*1.1,t_range(2)*0.95,['generated by Xscale\_scales.m ' datestr(now)] );
set(ht,'fontsize',6,'horizontalalignment','left','verticalalignment','top');

% RPW instrument sampling scales
f_spin=0.25;t_spin=4; % spin frequency and period
line(l_range(2)*[0.03 11], [t_spin t_spin])
ht=text(l_range(2)*0.9,t_spin*1.1,'spin period');
set(ht,'fontsize',14,'horizontalalignment','right','verticalalignment','baseline');

f=100;tt=1/f; % frequency 
line(l_range(2)*[0.03 11], [tt tt])
ht=text(l_range(2)*0.9,tt*1.1,'fields NM');
set(ht,'fontsize',14,'horizontalalignment','right','verticalalignment','baseline');

f=10000;tt=1/f; % spin frequency 
line(l_range(2)*[0.03 11], [tt tt])
ht=text(l_range(2)*0.9,tt*1.1,'fields BM');
set(ht,'fontsize',14,'horizontalalignment','right','verticalalignment','baseline');

f=100e3;tt=1/f; % spin frequency 
line(l_range(2)*[0.03 11], [tt tt])
ht=text(l_range(2)*0.9,tt*1.1,'fields superburst');
set(ht,'fontsize',14,'horizontalalignment','right','verticalalignment','baseline');

[hp,ht]=text_square(l_rho_range,t_range(1)*[1.25 3],1,[0.5 1 0.5],'ion scale');
[hp,ht]=text_square(l_erho_range,t_range(1)*[1.25 3],1,[0.5 1 0.5],'e- scale');
[hp,ht]=text_square(l_deb_range,t_range(1)*[1.25 3],1,[0.5 1 0.5],'Debye length');

[hp,ht]=text_square(l_range(1)*[1.2 2.6],t_cp_range,1,[0.8 0.8 1],'f_{ci}');
[hp,ht]=text_square(l_range(1)*[1.2 2.6],t_lh_range,1,[0.8 0.8 1],'f_{LH}');
[hp,ht]=text_square(l_range(1)*[1.2 2.6],t_ce_range,1,[0.8 0.8 1],'f_{ce}');
[hp,ht]=text_square(l_range(1)*[1.2 2.6],t_pe_range,1,[0.8 0.8 1],'f_{pe}');

[hp,ht]=text_square([l_deb_range(1) l_erho_range(2)],[t_pe_range(2) t_ce_range(1)],1,[1 1 0.7],'e- physics');
[hp,ht]=text_square([l_rho_range(1) l_rho_range(2)],[sqrt(t_lh_range(1)*t_lh_range(2)) t_cp_range(1)*2],1,[1 1 0.7],'ion physics');
[hp,ht]=text_square([6.372e3 1e5],[50 1000],1,[1 1 0.7],'fluid physics');

[hp,ht]=text_square([l_erho_range(2)/2 l_rho_range(1)*2],[t_ce_range(1)/2 t_lh_range(1)],0.5,[1 0.7 0.7],'e-/ion \newline coupling');
[hp,ht]=text_square([l_rho_range(2)/2 1e4],[t_cp_range(1)/2 200],0.5,[1 0.7 0.7],'ion/fluid \newline coupling');


title('Characteristic scales encountered by Cross-Scale');

% -----------------------------------------
function [hp,ht]=text_square(xint,yint,z,color,textit)
hp=patch([xint(1) xint(2) xint(2) xint(1)], [yint(1) yint(1) yint(2) yint(2)],[z z z z], color);
set(hp,'FaceAlpha',1,'LineWidth',1)
ht=text(sqrt(xint(1)*xint(2)),sqrt(yint(1)*yint(2)),z,textit);
set(ht,'fontsize',14,'HorizontalAlignment','center','VerticalAlignment','middle');
end
end
