% plot figure showing typical plasma densities and temperatures
% expected by Xscale 
function Xscale_plasma

n_range=[1e-2 1e2]; % density in cc
T_range=[1 3e4]; % temperature in eV

figure(1);
set(1,'Position',[0 0 650 500]);
clf;

h=subplot(1,1,1);
set(gca,'xscale','log','xlim',n_range);
set(gca,'yscale','log','ylim',T_range);
color_order=[0 0 0;1 0 0;0 0 1;0 0.6 0; 1 0 1];
set(gca,'linewidth',2,'MinorGridLineStyle','none','FontSize',14,'ColorOrder',color_order);
grid on;hold on;
ylabel('temperature [eV]');
xlabel('density [cm^{-3}]');

text_square([.1 .8],[1e3 20e3],1,[1 0.6 0.6],{'Reconnection','Turbulence','','\beta\geq 1','plasma sheet'});
text_square([3 20],[1.2 25],1,[0.7 0.7 1],{'Shocks','Turbulence','','\beta\leq 1', 'solar wind'});
text_square([5 90],[20 800],0.9,[0.8 1 0.7],{'Reconnection','Turbulence','','\beta\geq 1','shocked','solar wind'});
text_square([.12 8],[40 2000],0.8,[1 0.8 0.8],{'Reconnection','Turbulence','','\beta wide range','magnetopause'});
text_square([.012 0.12],[20 200],1,'y',{'Reconnection','','\beta<<1','lobes'});

% info line
add_labels=input('Add labels? y/n >','s');
if strcmp(add_labels,'y'),
    ht=text(n_range(1)*1.1,T_range(2)*0.95,['generated by Xscale\_plasma.m ' datestr(now)] );
    set(ht,'fontsize',6,'horizontalalignment','left','verticalalignment','top');
    title('Cross-Scale science in different plasmas');
end

% -----------------------------------------
function [hp,ht]=text_square(xint,yint,z,color,textit)
hp=patch([xint(1) xint(2) xint(2) xint(1)], [yint(1) yint(1) yint(2) yint(2)],[z z z z], color);
set(hp,'FaceAlpha',1,'LineWidth',1,'edgecolor','none')
ht=text(sqrt(xint(1)*xint(2)),sqrt(yint(1)*yint(2)),z,textit);
set(ht,'fontsize',12,'HorizontalAlignment','center','VerticalAlignment','middle','interpreter','tex');
end
end