% plot figure showing typical plasma densities and temperatures
% expected by Xscale 
function Xscale_beta
% beta = 0.4 n[cc] T[eV] / B^2[nT²]
% e- plasma freq [kHz]    = 9 sqrt(n [cc])
% e- gyrofreq [Hz]        = 28 B[nT]
% fp/fce = 9/28 sqrt(n[cc])/B[nT]

beta_range=[1e-3 1e2]; % plasma beta
fpfce_range=[1e-1 3e4]; % fce/fp

figure(1);
set(1,'Position',[0 0 600 1000]);
clf;
h=subplot(2,1,1);
set(gca,'xscale','log','xlim',beta_range);
set(gca,'yscale','log','ylim',fpfce_range);
color_order=[0 0 0;1 0 0;0 0 1;0 0.6 0; 1 0 1];
set(gca,'linewidth',2,'MinorGridLineStyle','none','FontSize',14, ...
    'ColorOrder',color_order);
grid on;hold on;
ylabel('f_{p}/f_{ce}');
xlabel('\beta');

text_square([.001 0.1],[100 2e3],1,[0.8 1 0.8],{'Lobes'})
text_square([.1 100],[300 3e3],1,[1 0.8 0.],{'Plasma sheet'})
text_square([.01 1],[3e3 14e3],0.9,[0.7 0.7 1],{'Solar wind'})
text_square([.001 0.03],[.3 3],0.8,[1 0.6 0.6],{'Lower corona'})
text_square([.04 0.2],[3 30],0.8,[1 0.8 0.8],{'Corona'})
text_square([.1 10],[30 500],1.1,[1 0.9 0.9],{'Outer Corona'})
%text_square([.015 0.1],[20 200],1,'y',{'Reconnection','','\beta<<1','lobes'})

% draw lines of plasma in convergent magnetic field beta=1/B^2
% fp/fce=1/B=sqrt(beta)
beta_start=1e-2;
beta_grid=beta_start:.1:beta_range(2);
fpfce_b_converg=fpfce_range(1)*sqrt(beta_grid/beta_start);
line(beta_grid,fpfce_b_converg);
text(beta_grid(1),fpfce_b_converg(1),'   plasma in convergent magnetic field','rotation',18,'verticalalignment','bottom','fontsize',12)
% info line
ht=text(beta_range(1)*1.1,fpfce_range(2)*0.95,['generated by Xscale\_beta.m ' datestr(now)] );
set(ht,'fontsize',6,'horizontalalignment','left','verticalalignment','top');

%title('Cross-Scale science in different plasmas');
subplot(2,1,2);axis off
plasmainfo=' lobes - B=10-30 nT, n=.1-1, T=100-200eV\newline ';
plasmainfo=[plasmainfo 'plasma sheet B=5-20nT, n=.1-1cc, T=1-10keV \newline '];
plasmainfo=[plasmainfo 'solar wind B=2-5nT, n=1-4cc, T=1-10eV \newline '];
plasmainfo=[plasmainfo 'corona B=10^6nT, n=10^9cc, T=100-300eV \newline '];
text(0,1,plasmainfo)

% -----------------------------------------
function [hp,ht]=text_square(xint,yint,z,color,textit)
hp=patch([xint(1) xint(2) xint(2) xint(1)], [yint(1) yint(1) yint(2) yint(2)],[z z z z], color);
set(hp,'FaceAlpha',0,'LineWidth',2)
ht=text(sqrt(xint(1)*xint(2)),sqrt(yint(1)*yint(2)),z,textit);
set(ht,'fontsize',12,'HorizontalAlignment','center','VerticalAlignment','middle','interpreter','tex');
end
end