%
% Hard-coded constants generated by code.
%
%
% Author: Erik P G Johansson, IRF, Uppsala, Sweden
%
classdef sconst
% PROPOSAL: Merge class back into bicas.const.
% PROPOSAL: Move to bicas.proc.L1L2.*.
%
% TODO: Abolish subtraction of k values in methods.
%
% NOTE: Feels like there should be a better way of implementing ASID, SSID,
%       SDIDs as uint8 + functions, but not sure how.
%
% PROPOSAL: Keep ASID, SSID, SDID as uint8 but also keep corresponding objects,
%           but defer functions on uint8 to object methods via dictionaries
%           uint8-->object.
%   Ex: C.SSID_OBJ_DICT(ssid).is_ASR()
%   PRO: More natural way of hardcoding information about each uint8 value.
%   CON: Akward to have two versions of ASID,SSID,SDID at the same time.
%     PRO: Separate names/abbreviations. 3-->2x3
%     CON: Use same abbreviations for both uint8 and objects.
%   CON: Still long calls.
%
%
% PROPOSAL: Hardcode information in structs (or objects) in private
%           dictionaries which bicas.sconst function implementations then use.
%   PRO: Automatic checks on uint8 (type), integer range (dictionary keys).
%   PRO: Does not need rely on adding/subtracting to translate between
%        ASID, SSID, SDID.
%
% PROPOSAL: Separate class constants for ASID, SSID, SDID respectively.
%   Replace .C --> .ASID (asid?) etc.
%   CON: Bad if wanting to "import" all constants at once.



  %###########
  %###########
  % CONSTANTS
  %###########
  %###########
  properties(Constant)



    C = bicas.sconst.init_const();



  end    % properties(Constant)



  %#######################
  %#######################
  % PUBLIC STATIC METHODS
  %#######################
  %#######################
  methods(Static, Access=public)



    % Define all constants for ASID, SSID, SDID, and Routing.
    %
    % IMPLEMENTATION NOTE: Defining one constant struct, which contains
    % multiple constants as fields. Makes it possible to access constants
    % through a variable copy of this constant rather than using the long
    % qualifiers.
    %
    % NOTE: Construction is problematic since bicas.proc.L1L2.Routing
    % constructors can not use other fields in bicas.sconst.C for assertions,
    % since it has not been initialized at that time. Also, bad syntax in this
    % code tends to give strange unintuitive error messages and error behaviour
    % in MATLAB.
    %
    % NOTE:
    function C2 = init_const()
      C2 = struct();

      C2.ASID_DICT          = configureDictionary('string', 'uint8');
      C2.ASID_CATEGORY_DICT = configureDictionary('uint8',  'string');
      C2.ASID_ANTENNAS_DICT = configureDictionary('uint8',  'cell');

      C2.SSID_DICT          = configureDictionary('string', 'uint8');
      C2.SSID_ASR_SET       = uint8([]);

      C2.SDID_DICT          = configureDictionary('string', 'uint8');
      C2.SDID_ASR_SET       = uint8([]);

      C2.ROUTING_DICT       = configureDictionary('string', 'bicas.proc.L1L2.Routing');

      % Global list of k values used for initializing ASIDs, SSIDs, and SDIS.
      % For avoiding collisions between all of them (for safety).
      kSet = [];

      function assert_new_k(k)
        assert(isnumeric(k))
        assert(~ismember(k, kSet))
        kSet(end+1) = k;
      end

      function add_ASR(s, k, asidCategory, asidAntennas)
        asid = uint8(k);

        C2.ASID_DICT(s)             = asid;
        C2.ASID_CATEGORY_DICT(asid) = asidCategory;
        C2.ASID_ANTENNAS_DICT(asid) = {asidAntennas};

        ssid = add_SSID(s, k);
        C2.SSID_ASR_SET(end+1, 1)   = ssid;

        sdid = add_SDID(s, k);
        C2.SDID_ASR_SET(end+1, 1)   = sdid;

        C2.ROUTING_DICT(s)          = bicas.proc.L1L2.Routing(ssid, sdid);
      end

      function ssid = add_SSID(s, k)
        ssid = uint8(k+100);
        assert_new_k(ssid)

        C2.SSID_DICT(s) = ssid;
      end

      function sdid = add_SDID(s, k)
        sdid = uint8(k+200);
        assert_new_k(sdid)

        C2.SDID_DICT(s) = sdid;
      end

      function main()
        % =====================================
        % Add every possible unique ASID object
        % =====================================
        add_ASR("DC_V1",  1, 'DC_SINGLE', [1   ]);
        add_ASR("DC_V2",  2, 'DC_SINGLE', [2   ]);
        add_ASR("DC_V3",  3, 'DC_SINGLE', [3   ]);

        add_ASR("DC_V12", 4, 'DC_DIFF',   [1, 2]);
        add_ASR("DC_V13", 5, 'DC_DIFF',   [1, 3]);
        add_ASR("DC_V23", 6, 'DC_DIFF',   [2, 3]);

        add_ASR("AC_V12", 7, 'AC_DIFF',   [1, 2]);
        add_ASR("AC_V13", 8, 'AC_DIFF',   [1, 3]);
        add_ASR("AC_V23", 9, 'AC_DIFF',   [2, 3]);

        add_SSID("REF25V",  10);
        add_SSID("GND",     11);
        add_SSID("UNKNOWN", 12);

        add_SDID("NOWHERE", 13);

        C2.ROUTING_DICT("REF25V_TO_DC_V1")    = bicas.proc.L1L2.Routing(C2.SSID_DICT("REF25V"),  C2.SDID_DICT("DC_V1"));
        C2.ROUTING_DICT("REF25V_TO_DC_V2")    = bicas.proc.L1L2.Routing(C2.SSID_DICT("REF25V"),  C2.SDID_DICT("DC_V2"));
        C2.ROUTING_DICT("REF25V_TO_DC_V3")    = bicas.proc.L1L2.Routing(C2.SSID_DICT("REF25V"),  C2.SDID_DICT("DC_V3"));
        C2.ROUTING_DICT("GND_TO_DC_V1")       = bicas.proc.L1L2.Routing(C2.SSID_DICT("GND"),     C2.SDID_DICT("DC_V1"));
        C2.ROUTING_DICT("GND_TO_DC_V2")       = bicas.proc.L1L2.Routing(C2.SSID_DICT("GND"),     C2.SDID_DICT("DC_V2"));
        C2.ROUTING_DICT("GND_TO_DC_V3")       = bicas.proc.L1L2.Routing(C2.SSID_DICT("GND"),     C2.SDID_DICT("DC_V3"));
        C2.ROUTING_DICT("UNKNOWN_TO_NOWHERE") = bicas.proc.L1L2.Routing(C2.SSID_DICT("UNKNOWN"), C2.SDID_DICT("NOWHERE"));

        assert(~ismember(255, kSet))
        assert(~ismember(0,   kSet))
      end

      main()
    end



    %======
    % ASID
    %======
    function isAsid = is_ASID(asidAr)
      assert(isa(asidAr, "uint8"))

      isAsid = all(ismember(asidAr, bicas.sconst.C.ASID_DICT.values), "ALL");
    end

    function asidCategory = get_ASID_category(asid)
      % TODO: Automated test.
      assert(isa(asid, "uint8") & isscalar(asid))

      asidCategory = bicas.sconst.C.ASID_CATEGORY_DICT(asid);
    end

    function antennas = get_ASID_antennas(asid)
      antennasCa = bicas.sconst.C.ASID_ANTENNAS_DICT(asid);
      antennas   = antennasCa{1};
    end

    function ssid = ASID_to_SSID(asid)
      assert(bicas.sconst.is_ASID(asid) & isscalar(asid))

      ssid = asid + 100;
      assert(bicas.sconst.is_SSID(ssid))
    end



    %======
    % SSID
    %======
    function isSsid = is_SSID(ssidAr)
      isSsid = all(ismember(ssidAr, bicas.sconst.C.SSID_DICT.values), "ALL");
    end

    function isAsr = SSID_is_ASR(ssid)
      assert(bicas.sconst.is_SSID(ssid) & isscalar(ssid))

      isAsr = any(find(bicas.sconst.C.SSID_ASR_SET == ssid));
    end

    function asid = SSID_ASR_to_ASID(ssid)
      assert(bicas.sconst.is_SSID(ssid) & isscalar(ssid))
      assert(bicas.sconst.SSID_is_ASR(ssid))

      asid = ssid - 100;
      assert(bicas.sconst.is_ASID(asid))
    end

    function isAc = SSID_is_AC(ssid)
      % TODO: Automated test.
      assert(bicas.sconst.is_SSID(ssid) & isscalar(ssid))

      if bicas.sconst.SSID_is_ASR(ssid)
        asid = bicas.sconst.SSID_ASR_to_ASID(ssid);
        isAc = (bicas.sconst.get_ASID_category(asid) == "AC_DIFF");
      else
        isAc = false;
      end
    end

    function isDiff = SSID_is_diff(ssid)
      % TODO: Automated test.
      assert(bicas.sconst.is_SSID(ssid) & isscalar(ssid))

      if bicas.sconst.SSID_is_ASR(ssid)
        asid = bicas.sconst.SSID_ASR_to_ASID(ssid);
        isDiff = ismember(bicas.sconst.get_ASID_category(asid), ["DC_DIFF", "AC_DIFF"]);
      else
        isDiff = false;
      end
    end



    %======
    % SDID
    %======
    function isSsid = is_SDID(sdidAr)
      assert(isa(sdidAr, "uint8"))

      isSsid = all(ismember(sdidAr, bicas.sconst.C.SDID_DICT.values), "ALL");
    end

    function isAsr = SDID_is_ASR(sdid)
      % TODO: Automated test.
      assert(bicas.sconst.is_SDID(sdid) & isscalar(sdid))

      isAsr = any(find(bicas.sconst.C.SDID_ASR_SET == sdid));
    end

    function asid = SDID_ASR_to_ASID(sdid)
      assert(bicas.sconst.is_SDID(sdid) & isscalar(sdid))
      assert(bicas.sconst.SDID_is_ASR(sdid))

      asid = sdid - 200;
      assert(bicas.sconst.is_ASID(asid))
    end

    function isNowhere = is_SDID_nowhere(sdid)
      % TODO: Automated test.
      assert(bicas.sconst.is_SDID(sdid) & isscalar(sdid))

      isNowhere = (sdid == bicas.sconst.C.SDID_DICT("NOWHERE"));
    end



  end    % methods(Static, Access=public)



end
