name: Bug Report
description: File a bug report
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out this bug report!"
  - type: checkboxes
    id: latestgit
    attributes:
      label: Issue is present in latest code
      description: "This issue is present in the most recent code (i.e. after running `git pull` this is still a problem)."
      options:
        - label: "I have run `git pull` and this issue is still present in the latest code."
          required: true
  - type: checkboxes
    id: matlab64bit
    attributes:
      label: Matlab 64bit
      description: "A 64bit install of Matlab is being used when encountering this issue."
      options:
        - label: "I am using a 64bit install of MathWorks Matlab."
          required: true
  - type: input
    id: os
    attributes:
      label: operatingsystem
      description: "Which operating system do you use? Please provide the version as well."
      placeholder: "e.g. 'macOS Big Sur 11.5.2', 'Ubuntu 22.04' or 'Windows 10'"
    validations:
      required: true
  - type: dropdown
    id: branch
    attributes:
      label: "Which branch of irfu-matlab are you using?"
      multiple: true
      options:
        - master
        - devel
        - MMSdevel
        - SOdevel
        - Other (please specify in "What happened" text below)
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: reproducability
    attributes:
      label: Reproduction steps
      description: "How do you trigger this bug? Please walk us through it step by step."
      value: |
        1. irf;
        2.
        3.
        ...
      render: MATLAB
    validations:
      required: true
  - type: textarea
    id: extrainfo
    attributes:
      label: Relevant log output or any other extra information.
      description: |
        Please copy and paste any relevant log output, if applicable. Or other information which may help us debug this issue.
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
