function addPlotInfo
% addPlotInfo add a string "created dd-mm-yy by user@host"
%
% $Revision$  $Date$

% Copyright 2004 Yuri Khotyaintsev
h1 = axes('Units','normalized', ...
	'Position',[0 0 1 1], ...
	'Visible','off', ...
	'Tag','BackgroundAxes');
[s,u] = unix('whoami');
[s,h] = unix('hostname');
u=u(1:end-1);h=h(1:end-1);
created_string = [ 'Created ' date ' by ' u '@' h];
h1 = text('Units','normalized', ...
	'FontSize',6, ...
	'HorizontalAlignment','left', ...
	'Position',[0.01 0.97], ...
	'String',created_string, ...
	'Tag','CreatedText');
