%
% Automatic test code
%
function translate___ATEST
    newTest = @(input, expOutputOrExcName) (EJ_library.atest.CompareFuncResult(...
        @EJ_library.utils.translate, ...
        input, ...
        expOutputOrExcName));
    
    tl = {};
    
    BEFORE_TABLE = {{}, {''}, {'qwe'}, {'QWE', 'ASD'}, {'z','x','c','v'}}';
    AFTER_TABLE  = {'will_never_be_after_value',2,'after_value', {}, struct()}';
    BA_TABLE = [BEFORE_TABLE, AFTER_TABLE];
    
    tl{end+1} = newTest(...
        {BA_TABLE, 'ASD', 'a:b', ''}, ...
        {{}});
    tl{end+1} = newTest(...
        {BA_TABLE, 'qwe', 'a:b', ''}, ...
        {'after_value'});
    tl{end+1} = newTest(...
        {BA_TABLE, 'z', 'a:b', ''}, ...
        {struct()});
    tl{end+1} = newTest(...
        {BA_TABLE, 'no such string', 'a:b', ''}, ...
        'MException');

    EJ_library.atest.run_tests(tl)
end