%
% matlab.unittest automatic test code for
% bepic.spinfit.fit_pot_SAFW().
%
%
% Author: Erik P G Johansson, IRF, Uppsala, Sweden
%
classdef spinfit_fit_pot_SAFW___UTEST < matlab.unittest.TestCase
  % PROPOSAL: More tests.



  %##############
  %##############
  % TEST METHODS
  %##############
  %##############
  methods(Test)



    function test_zero_timestamps(T)
      actT = bepic.spinfit.fit_pot_SAFW( ...
        tt2000Ar              = int64.empty(0, 1), ...
        spinPhaseRadAr        = double.empty(0, 1), ...
        samplesAr             = double.empty(0, 2), ...
        fitWindowPeriodRad    = 2*pi, ...
        fitWindowLengthRad    = 2*pi, ...
        fitWindowCenterRefRad = pi, ...
        dataGapMinNs          = int64(1000));

      T.verifyEqual(actT.fitWindowCenterTt2000, int64.empty( 0, 1))
      T.verifyEqual(actT.mean,                  double.empty(0, 2))
    end



    function test_one_timestamp(T)
      actT = bepic.spinfit.fit_pot_SAFW( ...
        tt2000Ar              = int64([10]'), ...
        spinPhaseRadAr        = [0.5]' * 2*pi, ...
        samplesAr             = [3, 4], ...
        fitWindowPeriodRad    = 2*pi, ...
        fitWindowLengthRad    = 2*pi, ...
        fitWindowCenterRefRad = pi, ...
        dataGapMinNs          = int64(1000));

      T.verifyEqual(actT.fitWindowCenterTt2000, int64.empty( 0, 1))
      T.verifyEqual(actT.mean,                  double.empty(0, 2))
    end



    function test_2_fit_windows(T)
      actT = bepic.spinfit.fit_pot_SAFW( ...
        tt2000Ar              = int64(    [ 01   06   11   16]'), ...
        spinPhaseRadAr        = wrapTo2Pi([0.1, 0.6, 0.1, 0.6]' * 2*pi), ...
        samplesAr             =           [  1, 6; 2, 7; 3, 8; 4, 9], ...
        fitWindowPeriodRad    = 2*pi*1, ...
        fitWindowLengthRad    = 2*pi*1, ...
        fitWindowCenterRefRad = 2*pi*0.5, ...
        dataGapMinNs          = int64(1000));

      T.verifyEqual(actT.fitWindowCenterTt2000, int64([  5;  15]))
      T.verifyEqual(actT.mean,                        [  1.5, 6.5; 3.5, 8.5])
    end



    % One NaN sample in each fit window.
    function test_NaN_sample_2_fit_windows(T)
      actT = bepic.spinfit.fit_pot_SAFW( ...
        tt2000Ar              = int64(    [ 01   06   11   16]'), ...
        spinPhaseRadAr        = wrapTo2Pi([0.1, 0.6, 0.1, 0.6]' * 2*pi), ...
        samplesAr             =           [  1, 6; NaN, 7; 3, NaN; 4, 9], ...
        fitWindowPeriodRad    = 2*pi*1, ...
        fitWindowLengthRad    = 2*pi*1, ...
        fitWindowCenterRefRad = 2*pi*0.5, ...
        dataGapMinNs          = int64(1000));

      T.verifyEqual(actT.fitWindowCenterTt2000, int64([  5;  15]))
      T.verifyEqual(actT.mean,                        [  1, 6.5; 3.5, 9])
    end



    % One data gap between fit windows.
    function test_2_fit_windows_data_gap(T)
      actT = bepic.spinfit.fit_pot_SAFW( ...
        tt2000Ar              = int64(    [ 01   06   1011   1016]'), ...
        spinPhaseRadAr        = wrapTo2Pi([0.1, 0.6, 0.1, 0.6]' * 2*pi), ...
        samplesAr             =           [  1, 6; 2, 7; 3, 8; 4, 9], ...
        fitWindowPeriodRad    = 2*pi*1, ...
        fitWindowLengthRad    = 2*pi*1, ...
        fitWindowCenterRefRad = 2*pi*0.5, ...
        dataGapMinNs          = int64(1000));

      T.verifyEqual(actT.fitWindowCenterTt2000, int64([  5;  1015]))
      T.verifyEqual(actT.mean,                        [  1.5, 6.5; 3.5, 8.5])
    end



  end    % methods(Test)



end
