% "Manual" test/demo of using other files in this package. MCALL = Manual call.
%
% UNFINISHED
%
%
% Created 2017-12-15 by Erik Johansson, IRF Uppsala.
%
function engine___MCALL
% PROPOSAL: Replace file by proper "demo"?
% PROPOSAL: Replace file by proper "scenario"?
%=======================================================================================
% Copied from Dropbox/JUICE/Engineering/Budget_Tables/ju_rpwi_tm_power.m 2018-01-02.
%   case 'GCO500'
%     seqIns = [
%       0    2; ...
%       20   4; ...
%       25   2; ...
%       60   4; ...
%       65   2; ...
%       385  4; ...
%       390  2; ...
%       425  4;
%       430  2;
%       960  1; ...
%       ];
%
%     seqRad = [
%       0    6; ...
%       62   7; ...
%       72   6; ...
%       425  8; ...
%       435 6; ...
%       500  7; ...
%       510  6; ...
%       ];
%     case 'GCO500ext_GC0200'
%       modeTitle = 'GCO500ext/GC0200';
%
%       seqIns = [
%         0    3; ...
%         20   4; ...
%         25   3; ...
%         425  4;
%         430  3;
%         960  1; ...
%         ];
%
%       seqRad = [
%         0    6; ...
%         425  8; ...
%         435 6; ...
%         ];
%=======================================================================================

[InSituModes, RadioModes] = TM_power_budget.default_instrument_modes();

% GCO500
seqInSitu = {
    0    'In-situ_slow'; ...
    20   'In-situ_burst'; ...
    25   'In-situ_slow'; ...
    60   'In-situ_burst'; ...
    65   'In-situ_slow'; ...
    385  'In-situ_burst'; ...
    390  'In-situ_slow'; ...
    425  'In-situ_burst';
    430  'In-situ_slow';
    960  'In-situ_low'; ...
    };
seqRadio = {
    0    'Radio_full'; ...
    62   'Radio_burst'; ...
    72   'Radio_full'; ...
    425  'Radar_mode-3'; ...
    435  'Radio_full'; ...
    500  'Radio_burst'; ...
    510  'Radio_full'; ...
    };
InSituModeSequence = struct('beginSec', {[seqInSitu{:, 1}]*60}, 'id', seqInSitu(:, 2));
RadioModeSequence  = struct('beginSec', {[ seqRadio{:, 1}]*60}, 'id', seqRadio (:, 2));

TM_power_budget.engine(InSituModes, RadioModes, InSituModeSequence, RadioModeSequence);
end
