classdef test_whamp_module < matlab.unittest.TestCase
  % test_whamp_module
  properties
    % Default whamp param
    PlasmaModel = struct('B', 100,...
      'Species', {{...
      struct(... 
        'm', 16, ...  % Oxygen
        'n', 1, ...
        't', 10, ...
        'a', 5, ...
        'b', 0, ...
        'd', 1, ...
        'vd', 1), ...
    struct(...
        'm', 0, ... % Electrons
        'n', 1, ...
        't', 100, ...
        'a', 1, ...
        'b', 0, ...
        'd', 1, ...
        'vd', 0)}} ...
      );
    InputParameters = struct(...
      'fstart', 0.1, ...
      'kperp', [0 10 0], ...
      'kpar', [0.002200000000000 10 0.002200000000000], ...
      'varyKzFirst', 1, ...
      'useLog', 0, ...
      'maxIterations', 50);
    output = [];
  end
  
  methods (TestClassSetup)
    function defaultRun(testCase)
      % Defaults (should be same as empty inputs)
      testCase.output = whamp.run([], []);
    end
  end
  
  methods (Test)
    function verify_default_run(testCase)
      % Verify we get information back about our inputs (and that it's the
      % same)
      testCase.verifyEqual(testCase.output.InputParameters, testCase.InputParameters);
      testCase.verifyEqual(testCase.output.PlasmaModel,     testCase.PlasmaModel);
    end
  end
end
