%
% "Playground code" for plotting & inspecting the transfer functions and
% kernels BICAS uses (when enabled).
%
% NOTE: This code is not meant to "elegant" in its entirety, but for being
% continually modified when inspecting TFs and kernels. It is e.g. expected to
% hard code paths to the RCTs being used, and not be entirely covered by tests.
%
%
% Author: Erik P G Johansson, IRF, Uppsala, Sweden
%
classdef tfkernel_playground
  % PROPOSAL: Better location, name.
  %   plot
  %   TF, kernel
  %   bicas.tools.tfkernel (class, not package)
  %   bicas.tools.tfkernel_playground (class, not package) -- IMPLEMENTED



  %#######################
  %#######################
  % PUBLIC STATIC METHODS
  %#######################
  %#######################
  methods(Static)



    function [Rctdc, Bso] = get_RCTDC_BSO()
      BIAS_RCT_PATH = '/nonhome_data/work_files/SOLAR_ORBITER/RCTs/RCTs_used_by_BICAS/solo_CAL_rpw-bias_20200210-20991231_V02.cdf';
      LFR_RCT_PATH  = '/nonhome_data/work_files/SOLAR_ORBITER/RCTs/RCTs_used_by_BICAS/solo_CAL_rpw-lfr-bias_20200210-20990101_V01.cdf';

      L = bicas.Logger('HUMAN_READABLE', false);

      Bso = bicas.create_default_BSO();
      Bso.make_read_only();

      % Read RCT files.
      BiasRctd =  bicas.proc.L1L2.cal.rct.findread.read_RCT_modify_log(...
        'BIAS', BIAS_RCT_PATH, L);
      LfrRctd  = bicas.proc.L1L2.cal.rct.findread.read_RCT_modify_log(...
        'LFR',  LFR_RCT_PATH, L);

      Rctdc = bicas.proc.L1L2.cal.RctdCollection();
      Rctdc.add_RCTD('LFR',  {LfrRctd});
      Rctdc.add_RCTD('BIAS', {BiasRctd});
    end



    function [Vcal, Bso] = get_VCAL_BSO()
      [Rctdc, Bso] = bicas.tools.tfkernel_playground.get_RCTDC_BSO();

      useNbci    = false;
      useGactRct = false;

      Vcds = bicas.proc.L1L2.cal.VoltageCalibrationDataSupplierImpl(Rctdc, useNbci, Bso);
      Vcal = bicas.proc.L1L2.cal.VoltageCalibration(Vcds, useGactRct, Bso);
    end



    % NOTE: Only currently supports LFR+BIAS (not TDS+BIAS).
    %
    % ~BUG: Does not entirely reproduce the ITFs and therefore kernels
    % generated by BICAS since it does not account for the TF modification
    % bicas.tf.apply_TF() does, i.e. truncating the TF at high frequencies.
    % BICAS needs to be modified further to make this easy & reliable.
    %
    function plot_IRFs_kernels___PLAYGROUND()
      [Vcal, Bso] = bicas.tools.tfkernel_playground.get_VCAL_BSO();

      function plot_ITF_kernel(ssidStr, iLsf)
        iBlts       = 1;
        ssid        = bicas.proc.L1L2.const.C.SSID_DICT(ssidStr);
        isAchg      = 0;   % double!!
        iCalibTimeL = 1;
        iCalibTimeH = 1;

        CalSettings = bicas.proc.L1L2.cal.CalibrationSettings(...
          iBlts, ssid, isAchg, iCalibTimeL, iCalibTimeH, iLsf);

        [itfAvpt, ~] = Vcal.get_voltage_calibration_ITF_offset(...
          isLfr       = true, ...
          isTdsCwf    = false, ...
          CalSettings = CalSettings, ...
          NbriFpa     = bicas.utils.FPArray(1, 'NO_FILL_POSITIONS'), ...
          NbciFpa     = bicas.utils.FPArray(1, 'NO_FILL_POSITIONS'));

        %lenKernel = Bso.get_fv('PROCESSING.CALIBRATION.TF.KERNEL.MAX_LENGTH_SAMPLES');
        lenKernel = 1024;

        dtSec     = 1 / solo.hwzv.const.LSF_HZ(iLsf);
        [yKernel, iKernelOrigin] = bicas.tf.time.get_raw_kernel(lenKernel, dtSec, itfAvpt);

        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

        t = [(-iKernelOrigin+1):(lenKernel-iKernelOrigin)] * dtSec;
        titleStr = sprintf(...
          "ssidStr=%s, iLsf=%d; lenKernel=%d; dtSec=%d; lenKernel*dtSec=%g; 1/dtSec=%d [Hz]", ...
          irf.graph.escape_str(ssidStr), ...
          iLsf, lenKernel, dtSec, lenKernel*dtSec, 1/dtSec);

        Fig = figure();
        Fig.WindowState = "maximized";

        subplot(2,1, 1)
        % NOTE: Has not managed to create separate grids for the two y axes.
        omegaRps = linspace(0, 1/dtSec*2);
        zAvpt    = itfAvpt(omegaRps);
        title(titleStr)
        yyaxis left
        plot(omegaRps, abs(zAvpt))
        ylabel('abs(Z(omega)) [Avolt/TM unit]')
        grid on
        yyaxis right
        plot(omegaRps, angle(zAvpt))
        xlabel('omega [rad/s]')
        ylabel('angle(Z(omega)) [rad]')

        subplot(2,1, 2)
        plot(t, yKernel, '.-')
        xlabel('t [s]')
        grid on
        zoom on

      end

      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

      close all

      plot_ITF_kernel("DC_V1", 1);
      %plot_ITF_kernel("DC_V1", 2);
      %plot_ITF_kernel("DC_V1", 3);
    end



  end    % methods(Static)



end
