% Read raw BIAS standalone calibration file (table).
%
% Reads a file file on the format of the files generated by the actual BIAS standalone calibration campaign, and
% NOT files later converted into any more "convenient" format. It effectively reads a numeric table in
% a text file with a certain comment style and labels the columns according to arguments.
%
%
% ARGUMENTS AND RETURN VALUE
% ==========================
% columnFieldNamesList : Cell array of strings, one per file table column (left to right).
% data                 : struct with one field per column.
%
%
% IMPLEMENTATION NOTE: Code needs to be able to handle files with different numbers of columns.
%
function data = read_BSACT_file(filePath, columnFieldNamesList)

fId = fopen(filePath, 'r');

% ASSERTION
if fId == -1
    error('BICAS:read_BSACT_file:PathNotFound', 'Can not open file "%s".', filePath)
end
fileContents = textscan(fId, '%f', 'CommentStyle', 'mheader');   % Format specification will read all numbers into one long 1D array.
fileContents = fileContents{1};
fclose(fId);

nColumns = length(columnFieldNamesList);

% ASSERTION. Tries to check for the number of columns, but is not a perfect test.
if mod(length(fileContents), nColumns) ~= 0
    error('BICAS:read_BSACT_file:UnexpectedFileFormat', 'Number of specificed columns does not match file contents.')
end
fileContents = reshape(fileContents, [nColumns, length(fileContents)/nColumns])';

data = struct;
for iColumn = 1:nColumns
    fieldName = columnFieldNamesList{iColumn};
    data.(fieldName) = fileContents(:, iColumn);
end

end
