%
% Helper function for extracting different kinds of symbols and
% colors given a index number
%
function symb=cefSymbolColormap(k)

mtr=[{'b-o'},    {'g-o'},    {'r-o'},    {'c-o'},    {'m-o'},    {'y-o'},    {'k-o'},...
    {'b-x'},    {'g-x'},    {'r-x'},    {'c-x'},    {'m-x'} ,   {'y-x'},    {'k-x'},...
    {'b-+'},    {'g-+'},    {'r-+'},    {'c-+'} ,   {'m-+'},    {'y-+'},    {'k-+'},...
    {'b-*'},    {'g-*'},    {'r-*'} ,   {'c-*'},    {'m-*'},    {'y-*'},    {'k-*'},...
    {'b-s'} ,   {'g-s'},    {'r-s'},    {'c-s'} ,   {'m-s'} ,   {'y-s'},    {'k-s'},...
    {'b-d'},    {'g-d'},    {'r-d'},    {'c-d'},    {'m-d'},    {'y-d'},    {'k-d'},...
    {'b-v'},    {'g-v'},    {'r-v'},    {'c-v'},    {'m-v'},    {'y-v'},    {'k-v'},...
    {'b-^'},    {'g-^'},    {'r-^'},    {'c-^'},    {'m-^'},    {'y-^'},   {'k-^'},...
    {'b-<'},    {'g-<'},    {'r-<'},    {'c-<'},    {'m-<'},    {'y-<'},    {'k-<'}];
symb=mtr(k);