%
% Hard-coded constants representing signal IDs and routings: ASID, SSID, SDID,
% and routings generated by code.
%
%
% IMPLEMENTATION NOTE: ASIDs, SSIDs, SDIDs are implemented as uint8 values for
% performance reasons. The implementation uses values per channel and CDF record
% which is too many instances for implementing them as objects, though that
% would have made the code simpler and more natural. This class supplies
% functions which replace the methods of such (non-existent) classes. The class
% ASID, (bicas.proc.L1L2.AntennaSignalId) is only for defining metadata
% associated with each uint8 value and to make the implementation of above
% mentioned method-replacing functions easier.
%
%
% SUMMARY OF CONSTANTS
% ====================
% Copy-pasted stdout from code.
% NOTE: The implementation is the authoritative source, not below table.
% --------------
% ASID:
% "DC_V1"  ⟼ 1
% "DC_V2"  ⟼ 2
% "DC_V3"  ⟼ 3
% "DC_V12" ⟼ 4
% "DC_V13" ⟼ 5
% "DC_V23" ⟼ 6
% "AC_V12" ⟼ 7
% "AC_V13" ⟼ 8
% "AC_V23" ⟼ 9
% --------------
% SSID:
% "DC_V1"   ⟼ 101
% "DC_V2"   ⟼ 102
% "DC_V3"   ⟼ 103
% "DC_V12"  ⟼ 104
% "DC_V13"  ⟼ 105
% "DC_V23"  ⟼ 106
% "AC_V12"  ⟼ 107
% "AC_V13"  ⟼ 108
% "AC_V23"  ⟼ 109
% "REF25V"  ⟼ 110
% "GND"     ⟼ 111
% "UNKNOWN" ⟼ 112
% -----------------
% SDID:
% "DC_V1"   ⟼ 201
% "DC_V2"   ⟼ 202
% "DC_V3"   ⟼ 203
% "DC_V12"  ⟼ 204
% "DC_V13"  ⟼ 205
% "DC_V23"  ⟼ 206
% "AC_V12"  ⟼ 207
% "AC_V13"  ⟼ 208
% "AC_V23"  ⟼ 209
% "NOWHERE" ⟼ 213
%
%
% Author: Erik P G Johansson, IRF, Uppsala, Sweden
%
classdef const
  % PROPOSAL: Rename class to something implying the theme of ASID, SSID, SDID
  %           rather than constants.
  %   PRO: Contains function relating to ASID, SSID, SDID.
  %   ~signal, ~channel
  %   ~address, ~label, ~source/destination
  %   ~id
  %   aid = Address ID(s)
  %   sid = Signal ID(s)
  %     PRO: Same components as in ASID, SSID, SDID.
  %     CON: Abbreviation occurs in many words
  %       Ex: "side", "outside", "inside", "consider", SSID/ASID
  %   cid = Channel ID(s)
  %     CON: "CID" is part of "QRCID", "decide", "incidence".
  %       CON: Is not a real abbrevation.
  %     CON: Does not deal with channels, more like addresses.
  %
  % PROPOSAL: Code for printing human-readable tables with values which can be
  %           copy-pasted to comments in this file.
  %
  % PROPOSAL: Rename ASID class AntennaSignalId.
  %   PRO: Clearer distinction between ASID class and uint8 values.
  %   CON: Different abbreviations?
  %   ~definition
  %   ~info, ~data, metadata
  %   ~BLTS
  %   --
  %   AntennaSignalDefinition
  %   AntennaSignalIdDefinition
  %   AntennaSignalIdInfo
  %
  % PROPOSAL: Abolish ASID uint8. Abolish SSID, SDID classes (keep ASID class?).
  %
  % PROPOSAL: Abolish ASID class.
  %   NOTE: ASID class is only instantiated in this file, and is
  %         most likely only used in this file too.
  %
  % PROPOSAL: Hardcode information in structs (or objects) in private
  %           dictionaries which bicas.proc.L1L2.const function implementations then use.
  %   PRO: Automatic checks on uint8 (type), integer range (dictionary keys).
  %   PRO: Does not need rely on adding/subtracting to translate between
  %        ASID, SSID, SDID.
  %
  %  PROBLEM: SSID_ASID_DICT.keys and SDID_ASID_DICT.keys are de facto
  %           the authoritative sets of SSID/SDID ASR values.



  %###########
  %###########
  % CONSTANTS
  %###########
  %###########
  properties(Constant)



    C = bicas.proc.L1L2.const.init_const();



  end    % properties(Constant)



  %#######################
  %#######################
  % PUBLIC STATIC METHODS
  %#######################
  %#######################
  methods(Static, Access=public)



    % Define all constants for ASID, SSID, SDID, and Routing.
    %
    % IMPLEMENTATION NOTE: Defining one constant struct, which contains
    % multiple constants as fields. Makes it possible to access constants
    % through a variable copy of this constant rather than using the long
    % qualifiers.
    %
    % NOTE: Construction is problematic since bicas.proc.L1L2.Routing
    % constructors can not use other fields in bicas.proc.L1L2.const.C for
    % assertions, since it has not been initialized at that time. Also, bad
    % syntax in this code tends to give strange unintuitive error messages and
    % error behaviour in MATLAB.
    %
    % NOTE:
    function C2 = init_const()
      C2 = struct();

      C2.ASID_DICT      = configureDictionary('string', 'uint8');
      C2.ASID_OBJ_DICT  = configureDictionary('uint8',  'bicas.proc.L1L2.AntennaSignalId');

      C2.SSID_DICT      = configureDictionary('string', 'uint8');
      C2.SSID_ASID_DICT = configureDictionary('uint8',  'uint8');    % Only ASR.

      C2.SDID_DICT      = configureDictionary('string', 'uint8');
      C2.SDID_ASID_DICT = configureDictionary('uint8',  'uint8');    % Only ASR.

      C2.ROUTING_DICT   = configureDictionary('string', 'bicas.proc.L1L2.Routing');

      % Global list of uint8 values used so far for defining ASIDs, SSIDs, and
      % SDIDs. This is used for avoiding collisions between all of the uint8
      % constants combined, not just within each category (for safety).
      allocatedUint8Ar = [];

      function allocate_new_uint8(k)
        assert(isnumeric(k))
        assert(~ismember(k, allocatedUint8Ar))
        allocatedUint8Ar(end+1) = k;
      end

      % (1) Add new SSID, SDID and ASID for the same ASR.
      % (2) Add Routing from ASR SSID to corresponding ASR SDID.
      function add_ASR_SSID_SDID_ASID_Routing(s, k, asidCategory, asidAntennas)
        asid = uint8(k);
        allocate_new_uint8(k)

        ssid = add_SSID(s, k);
        C2.SSID_ASID_DICT(ssid) = asid;

        sdid = add_SDID(s, k);
        C2.SDID_ASID_DICT(sdid) = asid;

        % Add ASID.
        AsidObj                = bicas.proc.L1L2.AntennaSignalId(ssid, asidCategory, asidAntennas);
        C2.ASID_DICT(s)        = asid;
        C2.ASID_OBJ_DICT(asid) = AsidObj;

        % Add Routing.
        C2.ROUTING_DICT(s)     = bicas.proc.L1L2.Routing(ssid, sdid);
      end

      % Add new SSID, only.
      function ssid = add_SSID(s, k)
        ssid = uint8(k+100);
        allocate_new_uint8(ssid)

        C2.SSID_DICT(s) = ssid;
      end

      % Add new SDID, only.
      function sdid = add_SDID(s, k)
        sdid = uint8(k+200);
        allocate_new_uint8(sdid)

        C2.SDID_DICT(s) = sdid;
      end

      function main()
        % Ensure that certain "magic" numbers are not used for ASID, SSID, or
        % SDID.
        allocate_new_uint8(0)
        allocate_new_uint8(255)

        % ===========================================
        % Add ASID, SSID, SDID for every possible ASR
        % ===========================================
        add_ASR_SSID_SDID_ASID_Routing("DC_V1",  1, "DC_SINGLE", [1   ]);
        add_ASR_SSID_SDID_ASID_Routing("DC_V2",  2, "DC_SINGLE", [2   ]);
        add_ASR_SSID_SDID_ASID_Routing("DC_V3",  3, "DC_SINGLE", [3   ]);

        add_ASR_SSID_SDID_ASID_Routing("DC_V12", 4, "DC_DIFF",   [1, 2]);
        add_ASR_SSID_SDID_ASID_Routing("DC_V13", 5, "DC_DIFF",   [1, 3]);
        add_ASR_SSID_SDID_ASID_Routing("DC_V23", 6, "DC_DIFF",   [2, 3]);

        add_ASR_SSID_SDID_ASID_Routing("AC_V12", 7, "AC_DIFF",   [1, 2]);
        add_ASR_SSID_SDID_ASID_Routing("AC_V13", 8, "AC_DIFF",   [1, 3]);
        add_ASR_SSID_SDID_ASID_Routing("AC_V23", 9, "AC_DIFF",   [2, 3]);

        % =======================
        % Add all remaining SSIDs
        % =======================
        add_SSID("REF25V",  10);
        add_SSID("GND",     11);
        add_SSID("UNKNOWN", 12);

        % =======================
        % Add all remaining SDIDs
        % =======================
        add_SDID("NOWHERE", 13);

        % ==================================================
        % Add all routings which are not ASR SSID-->ASR SDID
        % ==================================================
        C2.ROUTING_DICT("REF25V_TO_DC_V1")    = bicas.proc.L1L2.Routing(C2.SSID_DICT("REF25V"),  C2.SDID_DICT("DC_V1"));
        C2.ROUTING_DICT("REF25V_TO_DC_V2")    = bicas.proc.L1L2.Routing(C2.SSID_DICT("REF25V"),  C2.SDID_DICT("DC_V2"));
        C2.ROUTING_DICT("REF25V_TO_DC_V3")    = bicas.proc.L1L2.Routing(C2.SSID_DICT("REF25V"),  C2.SDID_DICT("DC_V3"));
        C2.ROUTING_DICT("GND_TO_DC_V1")       = bicas.proc.L1L2.Routing(C2.SSID_DICT("GND"),     C2.SDID_DICT("DC_V1"));
        C2.ROUTING_DICT("GND_TO_DC_V2")       = bicas.proc.L1L2.Routing(C2.SSID_DICT("GND"),     C2.SDID_DICT("DC_V2"));
        C2.ROUTING_DICT("GND_TO_DC_V3")       = bicas.proc.L1L2.Routing(C2.SSID_DICT("GND"),     C2.SDID_DICT("DC_V3"));
        C2.ROUTING_DICT("UNKNOWN_TO_NOWHERE") = bicas.proc.L1L2.Routing(C2.SSID_DICT("UNKNOWN"), C2.SDID_DICT("NOWHERE"));

        % =========================
        % Derive array of ASR SDIDs
        % =========================
        C2.SDID_ASR_AR = C2.SDID_ASID_DICT.keys;
      end

      main()
    end



    %======
    % ASID
    %======

    % Can handle array argument, but return value is scalar.
    function isAsid = is_ASID(asidAr)
      assert(isa(asidAr, "uint8"))
      isAsid = all(ismember(asidAr, bicas.proc.L1L2.const.C.ASID_DICT.values), "ALL");
    end

    % Not vectorized.
    function asidCategory = get_ASID_category(asid)
      assert(isscalar(asid))
      asidCategory = bicas.proc.L1L2.const.C.ASID_OBJ_DICT(asid).category;
    end

    % Not vectorized.
    function antennas = get_ASID_antennas(asid)
      assert(isscalar(asid))
      antennas = bicas.proc.L1L2.const.C.ASID_OBJ_DICT(asid).antennas;
    end

    % Vectorized.
    function bAcAr = ASID_is_AC(asidAr)
      assert(bicas.proc.L1L2.const.is_ASID(asidAr))

      bAcAr = ismember(asidAr, bicas.proc.L1L2.const.C.ASID_DICT(...
        ["AC_V12", "AC_V13", "AC_V23"]));
    end

    % Vectorized.
    function bDiffAr = ASID_is_diff(asidAr)
      assert(bicas.proc.L1L2.const.is_ASID(asidAr))

      bDiffAr = ismember(asidAr, bicas.proc.L1L2.const.C.ASID_DICT(...
        ["DC_V12", "DC_V13", "DC_V23", ...
        "AC_V12", "AC_V13", "AC_V23"]));
    end

    % Not vectorized.
    function ssid = ASID_to_SSID(asid)
      assert(isscalar(asid))
      ssid = bicas.proc.L1L2.const.C.ASID_OBJ_DICT(asid).ssid;
    end



    %======
    % SSID
    %======

    % Can handle array argument, but return value is scalar.
    function isSsid = is_SSID(ssidAr)
      assert(isa(ssidAr, "uint8"))

      isSsid = all(ismember(ssidAr, bicas.proc.L1L2.const.C.SSID_DICT.values), "ALL");
    end

    % Vectorized.
    function bAsrAr = SSID_is_ASR(ssidAr)
      assert(bicas.proc.L1L2.const.is_SSID(ssidAr))

      bAsrAr = ismember(ssidAr, bicas.proc.L1L2.const.C.SSID_ASID_DICT.keys);
    end

    % Not vectorized.
    % NOTE: Error if not ASR.
    function asid = SSID_ASR_to_ASID(ssid)
      assert(bicas.proc.L1L2.const.is_SSID(ssid) & isscalar(ssid))
      assert(bicas.proc.L1L2.const.SSID_is_ASR(ssid))

      asid = bicas.proc.L1L2.const.C.SSID_ASID_DICT(ssid);
    end

    % Vectorized.
    function bAcAr = SSID_is_AC(ssidAr)
      assert(bicas.proc.L1L2.const.is_SSID(ssidAr))

      bAcAr         = false(size(ssidAr));
      bAsrAr        = bicas.proc.L1L2.const.SSID_is_ASR(ssidAr);

      % IMPLEMENTATION NOTE: One could merge below commands but does not in
      % order to make it easier to examine which part is slow.
      ssidAsrAr     = ssidAr(bAsrAr);   % Fast
      % asidAr        = bicas.proc.L1L2.const.C.SSID_ASID_DICT(ssidAsrAr);   % Slow
      asidAr        = bicas.utils.dict_lookup(bicas.proc.L1L2.const.C.SSID_ASID_DICT, ssidAsrAr);   % Fast
      bAcAr(bAsrAr) = bicas.proc.L1L2.const.ASID_is_AC(asidAr);   % Fast
    end

    % Vectorized
    function bDiffAr = SSID_is_diff(ssidAr)
      assert(bicas.proc.L1L2.const.is_SSID(ssidAr))

      bDiffAr         = false(size(ssidAr));
      bAsrAr          = bicas.proc.L1L2.const.SSID_is_ASR(ssidAr);

      % IMPLEMENTATION NOTE: One could merge below commands but does not in
      % order to make it easier to examine which part is slow.
      ssidAsrAr       = ssidAr(bAsrAr);   % Fast
      % asidAr          = bicas.proc.L1L2.const.C.SSID_ASID_DICT(ssidAsrAr);   % Slow
      asidAr          = bicas.utils.dict_lookup(bicas.proc.L1L2.const.C.SSID_ASID_DICT, ssidAsrAr);   % Fast
      bDiffAr(bAsrAr) = bicas.proc.L1L2.const.ASID_is_diff(asidAr);   % Fast
    end



    %======
    % SDID
    %======

    % Can handle array argument, but return value is scalar.
    function isSsid = is_SDID(sdidAr)
      assert(isa(sdidAr, "uint8"))
      isSsid = all(ismember(sdidAr, bicas.proc.L1L2.const.C.SDID_DICT.values), "ALL");
    end

    % Not vectorized.
    function bAsrAr = SDID_is_ASR(sdid)
      assert(isscalar(sdid))
      assert(bicas.proc.L1L2.const.is_SDID(sdid))

      bAsrAr = ismember(sdid, bicas.proc.L1L2.const.C.SDID_ASR_AR);
    end

    % Not vectorized.
    % NOTE: Error if not ASR.
    function asid = SDID_ASR_to_ASID(sdid)
      assert(isscalar(sdid))
      assert(bicas.proc.L1L2.const.SDID_is_ASR(sdid))

      asid = bicas.proc.L1L2.const.C.SDID_ASID_DICT(sdid);
    end

    % Not vectorized.
    function bNowhere = SDID_is_nowhere(sdid)
      assert(bicas.proc.L1L2.const.is_SDID(sdid) & isscalar(sdid))
      bNowhere = (sdid == bicas.proc.L1L2.const.C.SDID_DICT("NOWHERE"));
    end



  end    % methods(Static, Access=public)



end
