%
% matlab.unittest automatic test code for bicas.proc.L1L2.qual, except for
% method bicas.proc.L1L2.qual.sliding_window_over_fraction().
%
%
% Author: Erik P G Johansson, IRF, Uppsala, Sweden
%
classdef qual___UTEST < matlab.unittest.TestCase



  %##############
  %##############
  % TEST METHODS
  %##############
  %##############
  methods(Test)



    % NOTE: Does not test setting NSO table
    %
    function test_get_quality_ZVs(testCase)
       % NOTE: Does not (truly) test the call to
       % bicas.proc.L1L2.qual.sliding_window_over_fraction().

       L = bicas.Logger("HUMAN_READABLE", false);

       N = 1;    % Bitmask for the lowest channel saturation quality bit.
       DATA = [...
         0 0 0 0 0 0 0 0 0   4  0 0; ...
         1 0 0 0 0 0 0 0 0   0  3 N* 1; ...
         0 1 0 0 0 0 0 0 0   0  3 N* 2; ...
         0 0 1 0 0 0 0 0 0   0  3 N* 4; ...
         0 0 0 0 0 0 0 0 0   4  0 0; ...
         0 0 0 1 0 0 0 0 0   0  3 N* 8; ...
         0 0 0 0 1 0 0 0 0   0  3 N*16; ...
         0 0 0 0 0 1 0 0 0   0  3 N*32; ...
         0 0 0 0 0 0 0 0 0   4  0 0; ...
         0 0 0 0 0 0 1 0 0   0  3 N* 8; ...
         0 0 0 0 0 0 0 1 0   0  3 N*16; ...
         0 0 0 0 0 0 0 0 1   0  3 N*32; ...
         0 0 0 0 0 0 0 0 0   4  0 0; ...
         1 1 1 1 1 1 0 0 0   0  3 N*(1+2+4 + 8+16+32); ...
         % Below: Both DC_V12 and AC_V12 saturation, but still only one bit set.
         0 0 0 1 0 0 1 0 0   0  3 N*8; ...
         0 0 0 0 1 0 0 1 0   0  3 N*16; ...
         0 0 0 0 0 1 0 0 1   0  3 N*32; ...
         ];
       N_ROWS     = size(DATA, 1);
       % NOTE: (Almost) only the size is important.
       TT2000_AR  = int64([1:N_ROWS] * 1e9)';
       % (iRec, iSdid)
       VSIB_AR_ALL                               = logical(DATA(:, 1:9));
       EXP_QUALITY_FLAG                          = uint8(  DATA(:, 10 ));
       EXP_L2_QUALITY_BITMASK_FULL_SATURATION    = uint16( DATA(:, 11 ));
       EXP_L2_QUALITY_BITMASK_CHANNEL_SATURATION = uint16( DATA(:, 12 ));

       VsibZvm = bicas.utils.ZvMap(N_ROWS);
       function add_channel(ssidStr, iVsib)
         ssid = bicas.proc.L1L2.const.C.SDID_DICT(ssidStr);
         VsibZvm.add(ssid, VSIB_AR_ALL(:, iVsib));
       end
       add_channel("DC_V1",  1)
       add_channel("DC_V2",  2)
       add_channel("DC_V3",  3)
       add_channel("DC_V12", 4)
       add_channel("DC_V13", 5)
       add_channel("DC_V23", 6)
       add_channel("AC_V12", 7)
       add_channel("AC_V13", 8)
       add_channel("AC_V23", 9)

       isSwf                     = false;
       vstbFractionThreshold     = 0.9;
       cwfSlidingWindowLengthSec = 1.01;

       NSO_TABLE_EMPTY = bicas.NsoTable(...
         int64.empty(0, 1), ...
         int64.empty(0, 1), ...
         string.empty(0, 1));

       % CALL TESTED FUNCTION
       [act_QUALITY_FLAG, act_L2_QUALITY_BITMASK] = ...
         bicas.proc.L1L2.qual.get_quality_ZVs( ...
         TT2000_AR, NSO_TABLE_EMPTY, "GLOBAL_SATURATION", VsibZvm, isSwf, ...
         vstbFractionThreshold, cwfSlidingWindowLengthSec, L);

       testCase.assertEqual(act_QUALITY_FLAG,       EXP_QUALITY_FLAG)
       testCase.assertEqual(act_L2_QUALITY_BITMASK, EXP_L2_QUALITY_BITMASK_FULL_SATURATION)

       % CALL TESTED FUNCTION
       [act_QUALITY_FLAG, act_L2_QUALITY_BITMASK] = ...
         bicas.proc.L1L2.qual.get_quality_ZVs( ...
         TT2000_AR, NSO_TABLE_EMPTY, "CHANNEL_SATURATION", VsibZvm, isSwf, ...
         vstbFractionThreshold, cwfSlidingWindowLengthSec, L);

       testCase.assertEqual(act_QUALITY_FLAG,       EXP_QUALITY_FLAG)
       testCase.assertEqual(act_L2_QUALITY_BITMASK, EXP_L2_QUALITY_BITMASK_CHANNEL_SATURATION)
    end



    function test_set_voltage_current_FV(testCase)

      function test(...
          zv_Epoch, zvUfv, ...
          SamplesZvm, zvCurrentAAmpere, ...
          ExpSamplesZvm, expZvCurrentAAmpere)

        nRows = irf.assert.sizes(...
          zv_Epoch,         [-1], ...
          zvCurrentAAmpere, [-1, 3]);
        assert(SamplesZvm.nRecords == nRows)
        L = bicas.Logger('NO_STDOUT', false);

        % NOTE: Modifies argument zvAsrSamplesAVoltSrm (handle object).
        actZvCurrentAAmpere = bicas.proc.L1L2.qual.set_voltage_current_FV(...
          zv_Epoch, SamplesZvm, zvCurrentAAmpere, zvUfv, L);

        ActSamplesZvm = SamplesZvm;
        testCase.verifyEqual(ActSamplesZvm,       ExpSamplesZvm)
        testCase.verifyEqual(actZvCurrentAAmpere, expZvCurrentAAmpere)
      end

      %===================================================================

      % Empty data.
      test( ...
        int64(zeros(0, 1)), ...
        false(0, 1), ...
        testCase.init_SamplesZvm(zeros(0, 1)), ...
        zeros(0, 3),  ...
        testCase.init_SamplesZvm(zeros(0, 1)), ...
        zeros(0, 3)  ...
        )

      % Non-empty input data that is not altered.
      test( ...
        int64([10, 11, 12, 13, 14]'), ...
        false(5, 1), ...
        testCase.init_SamplesZvm(zeros(5, 1)), ...
        zeros(5, 3),  ...
        testCase.init_SamplesZvm(zeros(5, 1)), ...
        zeros(5, 3)  ...
        )

      % Non-empty input data that is altered: 1 unaltered + 1 altered
      test( ...
        int64([10, 11]'), ...
        logical([0, 1]'), ...
        testCase.init_SamplesZvm([1, 2]'), ...
        [1:3; 11:13],  ...
        testCase.init_SamplesZvm([1, NaN]'), ...
        [1:3; NaN(1, 3)] ...
        )
      % Non-empty input data that is altered: 2 unaltered + (1+2) altered
      test( ...
        int64([10, 11, 12, 13, 14]'), ...
        logical([0, 1, 0, 1, 1]'), ...
        testCase.init_SamplesZvm([1, 2, 3, 4, 5]'), ...
        [1:3; 11:13; 21:23; 31:33; 41:43],  ...
        testCase.init_SamplesZvm([1, NaN, 3, NaN, NaN]'), ...
        [1:3; NaN(1,3); 21:23; NaN(2,3)] ...
        )
    end



  end    % methods(Test)



  %########################
  %########################
  % PRIVATE STATIC METHODS
  %########################
  %########################
  methods(Static, Access=private)



    % Utility function for creating a simplified SamplesZvm with identical
    % values on every channel.
    function SamplesZvm = init_SamplesZvm(samplesAr)
      assert(iscolumn(samplesAr))

      SamplesZvm = bicas.utils.ZvMap(numel(samplesAr));
      for asrSdid = bicas.proc.L1L2.const.C.SDID_ASR_AR'
        SamplesZvm.add(asrSdid, samplesAr);
      end
    end



  end    % methods(Static, Access=private)



end
