# This is a basic CI build workflow using GitHub Actions

name: ci-build

# Controls when the action will run.
on:
  # Triggers this workflow on push to master, devel, MMSdevel or SOdevel. Or pull requests to devel.
  push:
    branches: [ master, devel, MMSdevel, SOdevel ]
  pull_request:
    branches: [ devel ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # Job called "matlab" which runs selected tests for the latest version of MATLAB.
  matlab:
    # Runs Matlab
    #runs-on: ubuntu-latest
    ## Specify ubuntu-20.04 (as per 2023-12-02T15:30CET) since "ubuntu-latest" was changed to "ubuntu-22.04"
    # which may or may not have correct gfortran versions used for some compiled code in its repo.
    # ("libgfortran5" used for tests of +whamp/ and contrib/libirbem/).
    runs-on: ubuntu-20.04
    steps:
      # Check-out repository
      - uses: actions/checkout@v4

      # Install MATLAB (GitHub action provided by MathWorks)
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          products: MATLAB Parallel_Computing_Toolbox Image_Processing_Toolbox Financial_Toolbox Signal_Processing_Toolbox

      # Install required runtime lib for Fortan (whamp mex file)
      - name: Install libgfortran5
        run: |
          sudo apt-get update
          sudo apt-get install libgfortran5

      # Run MATLAB code
      - name: Run commands
        uses: matlab-actions/run-command@v2
        with:
          command: tests_before_release;

      # upload artifact (pdf report with plots, etc.)
      - uses: actions/upload-artifact@v4
        with:
          name: test_report.pdf
          path: ciPath/report.pdf
          retention-days: 1

  # Job which runs selected tests for MATLAB R2020a.
  matlab_R2020a:
    # Runs Matlab
    #runs-on: ubuntu-latest
    ## Specify ubuntu-20.04 (as per 2022-12-02T15:30CET) since "ubuntu-latest" was changed to "ubuntu-22.04"
    # which does not appear to have "libgfortran4" (used for tests of +whamp/) in its repo.
    runs-on: ubuntu-20.04

    # Only run job on SOdevel to reduce amount of run time at GitHub (limited resource).
    if: github.ref == 'refs/heads/SOdevel'
    steps:
      # Check-out repository
      - uses: actions/checkout@v4

      # Install MATLAB (GitHub action provided by MathWorks)
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2020a
          products: MATLAB Parallel_Computing_Toolbox Image_Processing_Toolbox Financial_Toolbox

      # Run MATLAB code
      - name: Run commands
        uses: matlab-actions/run-command@v2
        with:
          command: tests_before_release_R2020a;

      # Upload artifact (pdf report with plots, etc.)
      - uses: actions/upload-artifact@v4
        with:
          name: test_report_R2020a.pdf
          path: ciPath/report_R2020a.pdf
          retention-days: 1
